### ISSUE TITLE
Set default TargetFramework in NoTargets so projects don't need to specify it

### ISSUE THREAD

**Issue by jeffkl** [microsoft/MSBuildSdks#100]
SDK-style project must specify a TargetFramework to load properly in Visual Studio.  If the NoTarets SDK specified a TargetFramework, projects would not have to.

One drawback would be picking the default.  If the default is `net46` but a user happens to consume a package that doesn't support that framework, they'd get a restore error when they aren't even setting a TargetFramework.  So we'd need to determine the most compatible target framework or find a way to turn of the compatibility check all together since NoTargets projects don't need it.

Related to #97

**Comment by wjk** [comment]
I don't think that this will work as well as you might think. When loading a `*.csproj` file (regardless of the SDK it uses, if any) VS currently looks for a `TargetFramework` property in the project file, and if it is not found, then the project will be opened in the legacy project system. This causes all sorts of trouble, including project-migration popups and automated rewriting of the project file (which destroys all comments and blank lines in the file); it also disables right-click > Edit Project. I don't know if this behavior also affects `*.msbuildproj` files. There's an issue open in dotnet/project-system that discusses adding to/modifying this algorithm, but I can't seem to find it right now. You'll want to consult with them team on this one. Hope this helps!

**Comment by jeffkl** [comment]
I did some investigation and @wjk is right.  Visual Studio will not load a project unless it has the legacy layout or is SDK-style with a `<TargetFramework />` property.  I'll leave this issue open in case I can ever get it to work in future versions of Visual Studio.

**Comment by jeffkl** [comment]
Closing this issue since there's no way to do this
