### ISSUE TITLE
Microsoft.Build.NoTargets does not define "Test" target

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/MSBuildSdks#109]
I wanted to dogfood `Microsoft.Build.NoTargets` in the project system. Doing so I get error:

> error MSB4057: The target "Test" does not exist in the project.

...as seen in [this build](https://dev.azure.com/dnceng/public/_build/results?buildId=232907).

Is `Test` a standard target that should also be included here?

**Comment by jeffkl** [comment]
The "Test" target is not standard.  Generally you build and then run tests in a separate process.  Like:

```
msbuild.exe foo.csproj
vstest.console.exe bin\Debug\foo.dll
```

I think ProjectSystem is using Arcade which specifies a Test target:

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.targets#L22

You might need to ask the Arcade folks how to proceed.  You probably don't want the NoTargets project running tests but if it imports the Arcade test targets then the target should at least be defined but not do anything.

**Comment by drewnoakes** [comment]
Thanks. I'll remove this project from build in the solution.
