### ISSUE TITLE
Question: does CentralPackageVersions support wildcards

### ISSUE THREAD

**Issue by renetitulaer** [microsoft/MSBuildSdks#111]
Hi,

I always want to reference the latest version. Does CentralPackageVersion support wildcards?

Thanks,
René

**Comment by jeffkl** [comment]
[MSBuild project SDKs](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019#how-project-sdks-are-resolved) like `Microsoft.Build.CentralPackageVersions` can only use exact versions.  So you must update that version manually.

The versions that CentralPackageVersions sets can be a wildcard so your [Packages.props](msbuild /t:Restore /bl /p:NuGetRestoreTargets=D:\NuGet.Client\src\NuGet.Core\NuGet.Build.Tasks\NuGet.targets /p:RestoreTaskAssemblyFile=D:\NuGet.Client\artifacts\NuGet.Build.Tasks\16.0\bin\Debug\net472\NuGet.Build.Tasks.dll SolutionPackagesConfig.sln) can be:

```
<Project>
  <ItemGroup>
    <PackageReference Update="Newtonsoft.Json" Version="12.*" />
  </ItemGroup>
</Project>
```
