### ISSUE TITLE
NoTargets should set IncludeBuildOutput to false so that Pack task does not attempt to include an assembly

### ISSUE THREAD

**Issue by TFTomSun** [microsoft/MSBuildSdks#116]
seems like dotnet pack expects an assembly in the output folder which is not generated of course:
 
error NU5026: Die im Paket einzubeziehende Datei "D:\Temp\_Demo\CrossCutting.Build\CrossCutting.Nunit\bin\Debug\netstandard1.1\CrossCutting.Nunit.dll

**Comment by jeffkl** [comment]
Looks like we need to set `IncludeBuildOutput`.  For now, you can work around this by setting it in your project:

```
<PropertyGroup>
  <IncludeBuildOutput>false</IncludeBuildOutput>
</PropertyGroup>
```
