### ISSUE TITLE
CentralPackageVersions: Microsoft.AspNetCore.All should be excluded

### ISSUE THREAD

**Issue by dfederm** [microsoft/MSBuildSdks#118]
Microsoft.AspNetCore.All is a package which isn't implicit but also should not have a version specified.

In the .NET Core SDK if you try to specify a version for this package you get:
```
warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.All' specified a Version of `[2.2.2]`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs
```

But then if you remove the version, you get this from CentralPackageVersions:
```
error : The package reference 'Microsoft.AspNetCore.All' must have a version defined in '<redacted>\Packages.props'
```

**Comment by dfederm** [comment]
Almost certainly needs the same fix as: https://github.com/microsoft/MSBuildSdks/commit/0347e81a9aaac5321bbbf2b7e29627eb1a7de833

**Comment by jeffkl** [comment]
This is fixed in [Microsoft.Build.CentralPackageVersions 2.0.46](https://www.nuget.org/packages/Microsoft.Build.CentralPackageVersions/2.0.46)
