### ISSUE TITLE
'dotnet publish --no-build' failed due to traversal sdk's publish target depends on build

### ISSUE THREAD

**Issue by yhvicey** [microsoft/MSBuildSdks#125]
See [This code section](https://github.com/microsoft/MSBuildSdks/blob/a8c9726f222a53c91c62e77ab5026ea102e2aabe/src/Traversal/Sdk/Sdk.targets#L75-L77), if one call `dotnet publish --no-build` the command will fail with below error:

```none
error NETSDK1085: The 'NoBuild' property was set to true but the 'Build' target was invoked.
```

**Comment by jeffkl** [comment]
Similar to https://github.com/microsoft/MSBuildSdks/commit/0a47e85168a7c66e98cfae88b2d027af7a594a7d#diff-caf5a6dbd5e3b63c9fab63a5106e9aac looks like we'll need to condition out the setting of PublishDepends on if the `NoBuild` property is set to true.

https://github.com/dotnet/cli/blob/20152b3beeec7b9157ab4688494b52cb2fffb190/src/dotnet/commands/dotnet-publish/PublishCommandParser.cs#L41

**Comment by yhvicey** [comment]
Is there any plan for publishing a new plan including this change?

**Comment by jeffkl** [comment]
Sure thing: https://github.com/microsoft/MSBuildSdks/releases/tag/Microsoft.Build.Traversal.2.0.19
