### ISSUE TITLE
Include a lower bound in the dependency version to ensure consistent restore results.

### ISSUE THREAD

**Issue by jmecosta** [microsoft/MSBuildSdks#130]
Hi,

i must be need some glasses or something, cant get around this error:

Restore completed in 68.13 ms for D:\prod\structures\DirectManipulation\Tekla.BIM.Utilities\Tekla.BIM.Utilities.csproj.
WARNING: NU1604: Project dependency Tekla.Common.Geometry does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\prod\structures\ObjDrop\NugetGenStuff\Tekla.BIM.Geometry\project.assets.json

I can see the package version we specified in the central store exists in one of the feeds, and i can install it... the first version in the feed is 4.5.1 and thats the one that gets intalled

    ".NETFramework,Version=v4.5.1": {
      "Tekla.Common.Geometry/4.5.1": {
        "type": "package",
        "compile": {

        },
        "runtime": {

        }
      },

can the reason for this be  that the packages dont include lib/net451 

![image](https://user-images.githubusercontent.com/1041352/65545884-f68d9e80-df1e-11e9-9a83-0f75a0d37ae1.png)

If i add the Version="4.5.9" into the project that everything restores fine and works... 

Can someone give a help with this one.

thanks

**Comment by jmecosta** [comment]
ok i think i found after going through the targs and props file. My project contain packages.config (empty ones) after removing the files it start working

**Comment by jabbera** [comment]
I ran into this same issue. You saved the day @jmecosta
