### ISSUE TITLE
Expose dotnet list package/reference functionality to traversal projects

### ISSUE THREAD

**Issue by MeikTranel** [microsoft/MSBuildSdks#131]
When using Traversal Projects with an all PackageReference (even setting PackageRestoreStyle via Directory.Build.props) workspace, `dotnet list Traversal.proj package` fails with message:

```
The project `D:\test\Traversal.proj` uses package.config for NuGet packages, while the command works only with package reference projects.
```

When trying to do `dotnet list Traversal.proj reference` we get:
```
There are no Project to Project references in project Traversal.proj.
```

In my opinion a traversal project should be able to produce a project and package dependency graph (or at least a table containing all packages).
I know this issue might be better fit for the dotnet cli, but i wanted feedback here first. Maybe im doing something wrong even.
[Here's a minimal repro although i don't think this cli feature works at all with traversal](https://github.com/microsoft/MSBuildSdks/files/3661296/traversal-minimalrepro.zip)

**Comment by jeffkl** [comment]
This should be easy to fix.  NuGet determines if the project supports PackageReference with this criteria:

https://github.com/NuGet/NuGet.Client/blob/9173d9bc53b5123d5cadec6cae513149d40505b0/src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/MSBuildAPIUtility.cs#L312

The Traversal SDK needs to set `RestoreProjectStyle`:

```xml
<PropertyGroup>
  <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
</PropertyGroup>
```
Which is what the .NET Core SDK does: https://github.com/dotnet/sdk/blob/0979dd3c53a8971a5434cf4bc68efd103fe5ea68/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L88

It works as long as you have added any package references already:

```
D:\MSBuildSdks>dotnet list dirs.proj package
Project 'dirs' has the following package references
   [net40]:
   Top-level Package             Requested   Resolved
   > Nerdbank.GitVersioning      2.3.151     2.3.151
   > StyleCop.Analyzers          1.0.2       1.0.2
```
