### ISSUE TITLE
Get package version from central store in projects

### ISSUE THREAD

**Issue by jmecosta** [microsoft/MSBuildSdks#132]
Hi,

cant find how to do this :) 

i am doing some custom deployments for nunit, and would like to take 1.0.3 from the central Packages.props to avoid duplicating the 1.0.3 i both central and in project.

```xml
<None Include="$(NuGetPackageRoot)NUnit.TeamCityEventListener\1.0.3\tools\**">
      <Link>Nunit\Addins\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
```

is there some function like
$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))

as
$([MSBuild]::GetPackageVersion('NUnit.TeamCityEventListener')) that should resolve to the current version either central or overridden?

thanks

**Comment by jeffkl** [comment]
Use the [GeneratePathProperty](https://github.com/NuGet/NuGet.Client/pull/2271) feature I added:

https://blog.dangl.me/archive/accessing-nuget-package-paths-in-your-net-sdk-based-csproj-files/

**Comment by jmecosta** [comment]
Alright, this is exactly what I was looking for. Thanks for implementing.

**Comment by jmecosta** [comment]
@jeffkl sorry, after all this is not work yet! can u confirm vs 2019.3 supports this for non web sdks?
![image](https://user-images.githubusercontent.com/1041352/66057573-a24b7580-e541-11e9-85c8-0de14041a267.png)

![image](https://user-images.githubusercontent.com/1041352/66057599-abd4dd80-e541-11e9-9b7b-cdd2458df6ca.png)

**Comment by jeffkl** [comment]
The name of the property is `$(PkgPackage_Name_With_Periods_Replaced_With_Underscores)`.

So the property for `NUnit.ConsoleRunner` is `$(PkgNUnit_ConsoleRunner)`.  

You can see them all in `obj\projectname.nuget.g.props`

**Comment by jmecosta** [comment]
Oh sorry. Need some glasses of course...
