### ISSUE TITLE
problems controlling what ends up in output folder

### ISSUE THREAD

**Issue by jmecosta** [microsoft/MSBuildSdks#133]
@jeffkl  hi again,

another issue that i think its related with cetral pacakges.. i have this in central

    <PackageReference Update="Tekla.Common.Geometry"                                Version="4.5.9"         ExcludeAssets="runtime" PrivateAssets="all" />

and in a unit test project i have this
``` xml
    <PackageReference Include="Tekla.Common.Geometry">
      <IncludeAssets>all</IncludeAssets>
      <ExcludeAssets>none</ExcludeAssets>
      <PrivateAssets>none</PrivateAssets> ()
    </PackageReference>
```

but for some reason the dlls are not being copied over to the test folder. so tests fail. 

if i rremove the  ExcludeAssets="runtime" PrivateAssets="all" from the central packages then it works fine. 

however this is not what im after, basically there are a few packages that are not supposed to be copied over to our bin folder by any projects... since this dll is put to private GAC folder we usually dont allow duplicated copies of this to bloat our packages 

Am i using this correctly? thanks again

**Comment by jeffkl** [comment]
MSBuild ordering matters in this situation.  The original `PackageReference` item is declared in the project as:

```xml
<PackageReference Include="Tekla.Common.Geometry" />
```

But then CentralPackageVersioning is doing an _update_:

```xml
<PackageReference Update="Tekla.Common.Geometry"
   Version="4.5.9" 
   ExcludeAssets="runtime"
   PrivateAssets="all" />
```

The update overrides what you have in your project and `ExcludeAssets="runtime"` tells the system to not copy the runtime assemblies to your output path.

I do not recommend using any IncludeAssets/ExcludeAssets/PrivateAssets in `Packages.props` unless that's what you want for every project.  You generally only want to set the version.

Each project should set IncludeAssets/ExcludeAssets/PrivateAssets as necessary.

**Comment by jmecosta** [comment]
In this case, i really have no other way around... one of the reasons why
we use this central approach is to ensure all versions are the same acrross
the 100s of projects. One consequence of this is that the output of all
those 100s of projects is also tightly locked to first avoid duplicate dlls
being shipped and the second to redude the overwall build time the
ammountof copying done (this is extremely important in a build farm)

The perfect for these scenarios is that there would be a option to disable
referce copy unless explicitly required. That was the reason ive moded to
central in hope this would do it trick.

I can workaroubd by using the packageversion var and copy those to output
but that is a very ugly solution in my case...

Tests are a special case, since they need the stuff to run and we tipically
have them in seprate folders to avoid copy violations and versions clashes..

Doing what u suggest its going to be loads of maintenance for users since
they again have to be touching the project file over and over again to
exclude those dlls bloathing the project files as in the old format

Do you have any other way for this?

**Comment by jeffkl** [comment]
You can have this in Packages.props:

```xml
<Project>
  <ItemGroup>
    <PackageReference Update="Tekla.Common.Geometry" Version="4.5.9" />
    <!-- All projects do not copy dependencies to the output folder except test projects -->
    <PackageReference Update="Tekla.Common.Geometry" ExcludeAssets="runtime" PrivateAssets="all"
       Condition="'$(IsTestProject)' != 'true' />
  </ItemGroup>
</Project>
```

That will only set the ExcludeAssets=Runtime for non test projects.

**Comment by jmecosta** [comment]
not very pretty but does the job!
![image](https://user-images.githubusercontent.com/1041352/66149794-836de180-e61c-11e9-9461-3c75767fa732.png)

excellent if there was a flag to do this :)
but thanks again.

By the way, any idea when central package management will arrive to nuget/visual studio. Notice thats its still in incubation.

**Comment by jeffkl** [comment]
I don't recommend it, but if you really want all PackageReferences to be ExcludeAssets=Runtime except test projects, you can have a single ItemDefinitionGroup instead:

```xml
<Project>
  <ItemDefinitionGroup Condition="'$(IsTestProject)' != 'true'">
    <PackageReference>
      <ExcludeAssets>Runtime</ExcludeAssets>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemDefinitionGroup>
</Project>
```

This sets default metadata for all `<PackageReference />` items and would allow you to remove the `PackageReference Update="package" ExcludeAssets="Runtime"` for all of the packages.

**Comment by jmecosta** [comment]
yes, i will probably not apply the exclusion to all because some projects will need to copy some references! i havent tested this scenario yet since so far i only go failures for files being copy to places where they shoundt be.

**Comment by jmecosta** [comment]
@jeffkl the proposed solutions works only in visual studio! if you run from command line with msbuild 
IsTestProject is not going to be evaluated correctly. problem seems comming from nuget.exe. When running from visual studio on the left
![image](https://user-images.githubusercontent.com/1041352/66254232-225d1f80-e77c-11e9-8488-a9bb4b180ce2.png)

this are properly marked as runtime assemblies, if running directly from command line those are not evaluated. If we remove  IsTestProject it works as expected. however i endup with loads of dlls in output..

**Comment by jeffkl** [comment]
Closing since there's a working solution
