### ISSUE TITLE
Can't get GlobalPackageReference to work with MinVer

### ISSUE THREAD

**Issue by larsw** [microsoft/MSBuildSdks#134]
Hi,

 I can't get the `GlobalPackageReference` feature to work with the `MinVer` nuget package. It seems that it only include `Analyzers` and `Build`, but AFAIK it should include `BuildMultiTargeting` and possibly `BuildTransitive` as well (re. https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)

**Comment by jeffkl** [comment]
You are correct, I'll update the IncludeAssets today and release a new version.  Thanks for reporting this!

**Comment by larsw** [comment]
Great. When can I expect the new package to be out on nuget.org?

**Comment by jeffkl** [comment]
https://www.nuget.org/packages/Microsoft.Build.CentralPackageVersions/2.0.52

**Comment by larsw** [comment]
Cheers!
