### ISSUE TITLE
Unable to upgrade project from 1.0.85 to 1.0.88

### ISSUE THREAD

**Issue by galloglach** [microsoft/MSBuildSdks#140]
When I try to update nuget package 'Microsoft.Build.NoTargets' from 1.0.85 to 1.0.88
I get this error message in the Error List windows of Visual Studio 2019 Preview 5.0
> Package 'Microsoft.Build.NoTargets 1.0.88' has a package type 'MSBuildSdk' that is not supported by project 'MyProject'.

The root of the csproj file is
`<Project Sdk="Microsoft.Build.NoTargets/1.0.85">`

It's a utility projects that does not compile an assembly, just runs some Tasks.

**Comment by jeffkl** [comment]
I just built this project without having `Microsoft.Build.NoTargets` version `1.0.88` and it worked:

```xml
<Project Sdk="Microsoft.Build.NoTargets/1.0.88">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <Target Name="CustomAction" AfterTargets="Build">
    <Message Text="This is a sample NoTargets project" Importance="High" />
  </Target>

</Project>
```

```
Microsoft (R) Build Engine version 16.5.0-preview-19562-03+d72e25031 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/21/2019 8:12:57 AM.
Restoring packages for C:\Users\jeffkl\AppData\Local\Temp\009ab98f-44cb-4b7a-9920-fe2a33474107...
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.build.notargets/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.build.notargets/1.0.88/microsoft.build.notargets.1.0.88.nupkg
Installing Microsoft.Build.NoTargets 1.0.88.
     1>Project "D:\MSBuildSdks\samples\NoTargets\SampleNoTargets\SampleNoTargets.csproj" on node 1 (CustomAction target(s)).
     1>CustomAction:
         This is a sample NoTargets project
     1>Done Building Project "D:\MSBuildSdks\samples\NoTargets\SampleNoTargets\SampleNoTargets.csproj" (CustomAction target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.20
```

I'm using an unreleased preview of the next version of Visual Studio 2019.  

Can you run this:

```
msbuild /bl
```

And attach the `msbuild.binlog` to this issue?

**Comment by galloglach** [comment]
Thanks @jeffkl,

your sample pointed me in the right direction.
My problem was I also had a package reference in my project!

`<PackageReference Include="Microsoft.Build.NoTargets" Version="1.0.85" />`

Removed it and now all's good and able to upgrade to 1.0.88
