### ISSUE TITLE
It would be nice if the *DependsOn properties were extensible

### ISSUE THREAD

**Issue by redoz** [microsoft/MSBuildSdks#142]
That way (unless I'm missing something and it's already possible) I could set ```TraversalGlobalProperties``` from inside a "pre-build" target.

**Comment by jeffkl** [comment]
DependsOn properties must be set outside of targets because they affect how targets run.  Did you mean to open this issue in the [MSBuild](https://github.com/microsoft/msbuild) repo?

**Comment by redoz** [comment]
No, I meant the BuildDependsOn, PreBuilsDependsOn etc property that you overwrite in the traversal targets file. I'd like to be able to add my own target to that list.

**Comment by jeffkl** [comment]
All of these properties are extensible, you just need to set them as properties outside of targets.

```xml
<Project>
  <PropertyGroup>
    <BuildDependsOn>MyCustomTarget:$(BuildDependsOn)</BuildDependsOn>
  </PropertyGroup>
  <Target Name="MyCustomTarget">
    <!-- Runs before Build -->
  </Target>
</Project>
```

You can also use BeforeTargets and AfterTargets to inject your target before and after targets without needing to use any *DependsOn properties.

```xml
<Project>
  <Target Name="MyCustomTarget" BeforeTargets="Build">
    <!-- Runs before Build -->
  </Target>
</Project>
```

**Comment by redoz** [comment]
I'll do some more testing tomorrow to see if I can get it working. Thanks!

**Comment by redoz** [comment]
I'm starting to feel like I'm doing this all wrong, but this is effectively what I tried to do:
```.csproj
<Project Sdk="Microsoft.Build.Traversal/2.0.24">
  <PropertyGroup>
    <BuildDependsOn>SetGlobalProperties;$(BuildDependsOn)</BuildDependsOn>
  </PropertyGroup>
  
  <Target Name="SetGlobalProperties">
    <PropertyGroup>
      <TraversalGlobalProperties>Version=1.2.3</TraversalGlobalProperties>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <ProjectReference Include="**\*.csproj" />
  </ItemGroup>
</Project>
```
But this doesn't work because it gets overwritten by the ```Microsoft.Common.targets``` import I believe.
Am I barking up the wrong tree here? Should I be doing this inside a ```Directory.Build.targets``` instead?

**Comment by jeffkl** [comment]
Your `BuildDependsOn` value is being overwritten by the built-in MSBuild targets:

https://github.com/microsoft/msbuild/blob/master/src/Tasks/Microsoft.Common.CurrentVersion.targets#L828

These are imported after your project's contents.  I'd suggest using AfterTargets or `Directory.Build.targets`.  If you do this operation in a target, you can't just set the property since the property is copied to the `ProjectReference` item group outside of a target.

So if you want to do it as a target:

```xml
<Project Sdk="Microsoft.Build.Traversal/2.0.24">
  <Target Name="SetGlobalProperties" BeforeTargets="Build">
    <ItemGroup>
      <ProjectReference Update="@(ProjectReference)"
                        AdditionalProperties="Version=1.2.3;%(AdditionalProperties)" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <ProjectReference Include="**\*.csproj" />
  </ItemGroup>
</Project>
```

But if you place it in `Directory.Build.targets`, you can just set the property (unless you need to get the value of the property by running a task or something):
```xml
<Project>
  <PropertyGroup>
    <TraversalGlobalProperties>Version=1.2.3</TraversalGlobalProperties>
  </PropertyGroup>
</Project>
```

Do you need to get the property values using advanced logic or are they static values that you can just hard code in `Directory.Build.targets`?

**Comment by redoz** [comment]
The values are calculated in a target, so when I'm back at work tomorrow I'll try the first approach. Sorry for the noise in your bug tracker and thank you for all the help, it's much appreciated!

**Comment by jeffkl** [comment]
You're welcome, glad I could help!

**Comment by redoz** [comment]
That did the trick, thanks again!

Do you want me to add this as an example to the readme.md for the Traversal project?
