### ISSUE TITLE
Artifacts potentially packs build scripts in wrong folder

### ISSUE THREAD

**Issue by chris-sekira** [microsoft/MSBuildSdks#145]
The Artifacts project has props/targets that get packed into the _buildCrossTargeting_ folder. According to the NuGet package folder layout [documentation](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory) this should be the _buildMultiTargeting_ instead. 

Unless this some kind of a legacy workaround/disambiguation, the folder should probably be renamed. 

If I'm wrong on this and there's documentation that you've found for using the _buildCrossTargeting_, I'd be very appreciated if you could attach a link so that I can bookmark it for myself and request it's addition to the linked documentation above.

**Comment by jeffkl** [comment]
NuGet renamed the folder and supports both at least for a while.  We should rename it.

https://github.com/NuGet/Home/issues/4098

**Comment by chris-sekira** [comment]
Ah, google failed me. If _buildMultiTargeting_ is the new standard, I'll look into submitting a change. 

The oldest supported framework used here is net46, which was released before the linked issue's decision to move to _buildMultiTargeting_. Any chance we'd need to support _buildCrossTargeting_ for anyone using older clients?

**Comment by jeffkl** [comment]
I can't think of a reason to keep both folders since people using older clients can just use an older package.  I think renaming the folder is the right solution.  Please feel free to contribute the change, otherwise I can get to it next week.

**Comment by chris-sekira** [comment]
@jeffkl I'll make the change during lunch.
