### ISSUE TITLE
GlobalPackageReferences not working with Xamarin projects?

### ISSUE THREAD

**Issue by Cheesebaron** [microsoft/MSBuildSdks#150]
Xamarin has no support for SDK style projects yet, I guess this might be the issue?

However, when adding the following in `Directory.Build.targets`:

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.52" />
</Project>
```

And creating a `Packages.props` file in the root of the repo, with the versions in there. No matter which packages are used it fails with: 

```
/Users/cheesebaron/git/repo/XamarinApp/XamarinApp.csproj : error : The package reference 'System.Reflection.Primitives' must have a version defined in '/Users/cheesebaron/git/repo/Packages.props'.
```

Looking at the output from a restore using msbuild, it seems like `@(_PackageReferenceWithVersion->Count())` is always evaluated to `0`.

**Comment by Cheesebaron** [comment]
OK. Moved the Sdk declaration into the Xamarin csproj files instead and stuff started to work.

However, Visual Studio for Mac does not like this at all. It starts adding back the Version attributes in the PackageReference nodes.

**Comment by jeffkl** [comment]
I am unable to repro this in Visual Studio 2019, I don't have a Mac to test it out on at the moment.

Directory.Build.targets
```xml
<Project>
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.52" />
</Project>
```

Packages.props
```xml
<Project>
  <ItemGroup>
    <PackageReference Update="System.Reflection.Primitives" Version="4.3.0" />
    <PackageReference Update="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.3" />
  </ItemGroup>
</Project>
```
Project's PackageReferences:
```xml
<ItemGroup>
  <PackageReference Include="System.Reflection.Primitives" />
  <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" />
</ItemGroup>
```

![image](https://user-images.githubusercontent.com/17556515/75279038-c1cc8e80-57bf-11ea-98a6-5832639aed7f.png)

I've attached a ZIP containing what I was using.  Please attach your minimal repro if this guidance doesn't fix things.
[xamarin-repro.zip](https://github.com/microsoft/MSBuildSdks/files/4251687/xamarin-repro.zip)

**Comment by Cheesebaron** [comment]
OK. It seems like the issue is when adding `<Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.52" />` in the top of a Xamarin.Android or Xamarin.iOS project, instead of adding it in the targets file. Then Visual Studio for Mac adds version on packages in those Xamarin projects.

You can see here, as soon as I save the csproj file in VS for Mac, it adds Version to the PackageReferences: https://youtu.be/L842AP7he9s 

[xamarin-repro.zip](https://github.com/microsoft/MSBuildSdks/files/4254141/xamarin-repro.zip)

**Comment by jeffkl** [comment]
Applications like Visual Studio and Visual Studio for Mac will add versions directly to the projects since they don't understand that something else is managing the versions.  You will need to manually clean them up after you add package references in the UI or you'll need to manually add package references in a text editor instead of using the UI.  Does VS for Mac always put the versions in the project now?

Loading and building projects should work just fine in all scenarios.  Is that now working?

**Comment by Cheesebaron** [comment]
@jeffkl yep, it is working now. Thank you for your patience. I think this can be closed now 👍
