### ISSUE TITLE
Add technology-specific SDK for WPF

### ISSUE THREAD

**Issue by wjk** [Microsoft/MSBuildSdks#16]
See https://github.com/Microsoft/MSBuildSdks/pull/8#issuecomment-374335063 for context.

**Comment by jeffkl** [comment]
Related to #15

**Comment by wjk** [comment]
My initial implementation of the WPF SDK can be found at [SunburstApps/MSBuildSdks](https://github.com/SunburstApps/MSBuildSdks/tree/987e289db9ebb8f0dabdac3785c494a876ef6d42).

**Comment by rainersigwald** [comment]
I don't think this needs to be an open issue any more. [WPF and WinForms will be supported in .NET Core SDK 3.0](https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/).
