### ISSUE TITLE
Examples in README.md are misleading

### ISSUE THREAD

**Issue by joshudson** [microsoft/MSBuildSdks#162]
Says `<Project Sdk="Microsoft.Build.NoTargets">` which doesn't work out of the box.

Should be `<Project Sdk="Microsoft.Build.NoTargets/version">`

**Comment by jeffkl** [comment]
Since the first section of the main README says how to use these SDKs, I'm going to close for now, unless someone thinks that's not enough

https://github.com/Microsoft/MSBuildSdks#how-can-i-use-these-sdks

**Comment by joshudson** [comment]
I went back and read the source control history. This got fixed about a month after I filed it. Thanks.
