### ISSUE TITLE
Traversal Package should honor Exclude Attribute

### ISSUE THREAD

**Issue by jeremytcorp** [microsoft/MSBuildSdks#172]
When using Microsoft.Build.Traversal, the Exclude attribute on the ProjectReference element isn't honored. I would expect it to remove all projects which are specified in the Exclude attribute.

``` xml
<Project Sdk="Microsoft.Build.Traversal">
  <ItemGroup>
    <!-- All Projects except Experimental Projects-->
    <ProjectReference Include="src\**\*.*proj" Exclude="src\Experimental\**\*.*proj"/>
  </ItemGroup>
</Project>
```

Expected outcome:
Only reference projects under the src directory that aren't under Experimental.

Actual outcome:
The Exclude attribute is ignored and all projects under source are included, even experimental ones

Note: The example I gave was a single use case. I have been attempting to include all projects except for a specific kind (vcxproj) or explicit project paths.

**Comment by jeffkl** [comment]
This is simple MSBuild, I see no reason that Traversal would cause such behavior.  I am not able to repro it with the attached project set.

Can you attach a repro?
[172-repro.zip](https://github.com/microsoft/MSBuildSdks/files/4594137/172-repro.zip)
```xml
<Project Sdk="Microsoft.Build.Traversal/2.0.34">
  <ItemGroup>
    <!-- All Projects except Experimental Projects-->
    <ProjectReference Include="src\**\*.*proj" Exclude="src\Experimental\**\*.*proj"/>
  </ItemGroup>
</Project>
```

```cmd
D:\Stuff\172-repro>msbuild
Microsoft (R) Build Engine version 16.7.0-preview-20251-04+8e4c57314 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/7/2020 9:05:56 AM.
Project "D:\Stuff\172-repro\dirs.proj" on node 1 (default targets).
Project "D:\Stuff\172-repro\dirs.proj" (1) is building "D:\Stuff\172-repro\src\one\one.proj" (2) on node 1 (default targets).
Build:
  Hello from D:\Stuff\172-repro\src\one\one.proj!
Done Building Project "D:\Stuff\172-repro\src\one\one.proj" (default targets).

Project "D:\Stuff\172-repro\dirs.proj" (1) is building "D:\Stuff\172-repro\src\two\two.proj" (3) on node 1 (default targets).
Build:
  Hello from D:\Stuff\172-repro\src\two\two.proj!
Done Building Project "D:\Stuff\172-repro\src\two\two.proj" (default targets).

Done Building Project "D:\Stuff\172-repro\dirs.proj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.36
```

**Comment by jeremytcorp** [comment]
For some reason, I can't repo after retrying this approach. Maybe I had some typos in my paths we didn't catch. Sorry for the noise and thanks for the verification.
