### ISSUE TITLE
TraversalSDK: Collect TargetOutputs of ProjectReference

### ISSUE THREAD

**Issue by MeikTranel** [microsoft/MSBuildSdks#181]
Similar to how the sln metaproj produces a collective TargetOutput of all projects built, the traversal SDK should list those when building as well.

**Expectation:**
Running
`msbuild C:/traversaltest/traverse.proj /t:Build`
```xml
<Project Sdk="Microsoft.Build.Traversal/2.0.34">
  <ItemGroup>
    <ProjectReference Include="a/a.csproj" />
    <ProjectReference Include="b/b.csproj" />
  </ItemGroup>
</Project>
```
should list:

C:/traversaltest/a/bin/debug/netcoreapp3.1/a.dll,
C:/traversaltest/b/bin/debug/netcoreapp3.1/b.dll

as TargetOutputs of target "Build".

While "Build" is my primary concern respective targetoutputs of other targets should certainly work the same way they do in the regular SDK.
_When testing this make sure to verify SDK behavior when using x-targeted projects because those might have some issues producing outputs from inner builds themselves._

**Comment by MeikTranel** [comment]
I could throw you a PR if you want ;)

**Comment by jeffkl** [comment]
Sounds like a great feature, feel free to send a PR.
