### ISSUE TITLE
Missing "Get Started" in Readme

### ISSUE THREAD

**Issue by peni4142** [microsoft/MSBuildSdks#188]
Hi developer :-)
I am looking for how I get started with the `Microsoft.Build.CentralPackageVersions`.
I have started a fresh `.NET CORE` Project but I can't add the `NuGet Package`. I get the error:
`Error Package 'Microsoft.Build.CentralPackageVersions 2.0.79' has a package type 'MSBuildSdk' that is not supported by project 'AppInsightsClient'.`

What do I have to do to get started?

**Comment by jeffkl** [comment]
Please see https://github.com/microsoft/MSBuildSdks#how-can-i-use-these-sdks

**Comment by peni4142** [comment]
If I do that it says, loading the project fails.

**Comment by peni4142** [comment]
Maybe you can answer the question on StackOverflow
https://stackoverflow.com/questions/62370155/how-to-use-microsoft-build-centralpackageversions

and improve the get started a little bit?

**Comment by jeffkl** [comment]
Here's a repo that uses it:

https://github.com/jeffkl/ManagedDism

You just create a `Directory.Build.targets` and reference the SDK package:

https://github.com/jeffkl/ManagedDism/blob/0a880f2bd6f8f2a17b3a0d1580a5ba2d3c49b7d1/Directory.Build.targets#L6

Then you create a file named `Packages.props` and add `<PackageReference Update="" />` items:

https://github.com/jeffkl/ManagedDism/blob/0a880f2bd6f8f2a17b3a0d1580a5ba2d3c49b7d1/Packages.props#L7

Then your projects reference the packages without versions:

https://github.com/jeffkl/ManagedDism/blob/0a880f2bd6f8f2a17b3a0d1580a5ba2d3c49b7d1/src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj#L10

**Comment by peni4142** [comment]
Thank you man!
