### ISSUE TITLE
Microsoft.Build.CentralPackageVersions README seems incomplete

### ISSUE THREAD

**Issue by bording** [Microsoft/MSBuildSdks#19]
The [README](https://github.com/Microsoft/MSBuildSdks/blob/master/src/CentralPackageVersions/README.md) for Microsoft.Build.CentralPackageVersions doesn't seem to show how to use this SDK. 

It shows how to create the Packages.props file and that you can't have versions for packages in your project files, but the actual Microsoft.Build.CentralPackageVersions SDK doesn't appear to be referenced anywhere in the examples.

What's the correct way to get this working?

**Comment by jeffkl** [comment]
All of the SDKs can be referenced depending on your needs according to this doc (which is linked to in the README):

https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk

CentralPackageVersions is the least likely to be referenced by individual projects and the best practice is to place an `<Sdk />` element in your `Directory.Build.targets`.

Sdk Element: https://docs.microsoft.com/en-us/visualstudio/msbuild/sdk-element-msbuild

Directory.Build.props/Directory.Build.targets: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build

I'll update the README of CentralPackageVersions with a sample, does that sound like enough?

**Comment by bording** [comment]
@jeffkl After opening this issue, I was able to use the MSBuild Project SDKs documentation along with information in https://github.com/Microsoft/msbuild/issues/2803 to figure out how to get it working.

I think updating the CentralPackageVersions README to have the SampleProject.csproj show it using the SDK would be a good idea. Adding something about referencing it via `Directory.Build.targets` being the preferred option seems like it would be useful, too.

On a side note, while looking at the documentation and the spec issue, I noticed that the documentation page doesn't say anything about being able to provide a semicolon-separate list of SDKS as shown in https://github.com/Microsoft/msbuild/issues/2803#issuecomment-362011005. Was that an intentional omission?

**Comment by jeffkl** [comment]
> I think updating the CentralPackageVersions README to have the SampleProject.csproj show it using the SDK would be a good idea

Agreed: https://github.com/Microsoft/MSBuildSdks/pull/22

> I noticed that the documentation page doesn't say anything about being able to provide a semicolon-separate list of SDKS... Was that an intentional omission?

I think so, we don't really want people using that syntax since the others are much cleaner.  But feel free to add to the docs: https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-use-project-sdk.md
