### ISSUE TITLE
Disable Project Reference TargetFramework Validation for NoTargets?

### ISSUE THREAD

**Issue by TheXenocide** [microsoft/MSBuildSdks#191]
We have an SDK derived from NoTargets and are trying to use it in the process of creating an installer. Sometimes these projects need to reference net48 projects and sometimes they need to reference netcoreapp2.1 projects. Since our NoTargets-based project isn't compiling anything, but rather copying files/applying scripts/etc. we were hoping to be able to reference without worrying about different target frameworks. To be clear, we're not trying to use multi-targeting with this project, it's goal is to have one output that can reference either or both project types. Is this feasible?

**Comment by jeffkl** [comment]
It probably won't work as-is today but you can try it.  I think we need to set these properties on ProjectReference items like we do in Traversal:

https://github.com/microsoft/MSBuildSdks/blob/5ab9834c63f037499e854705a1dbd66edaff4f72/src/Traversal/Sdk/Sdk.props#L33-L44

**Comment by TheXenocide** [comment]
Thanks for the info, we've tentatively worked around things, but we may have a chance to try some of these soon. If I manage to get any additional info on this I'll try to share it here, though admittedly this is being worked on by someone else on the team while I'm focused on other things.

**Comment by TheXenocide** [comment]
So it looks like this works for us. Thanks! I can see scenarios that would want to work both ways, so I'm not sure if there's a need to change the default behavior or if easier methods of control are called for, but we actually need some projects to work like normal project references at times so in our case it's actually helpful to be able to apply these on a per-project basis. I don't want to close the ticket in case you guys have ideas on improving the experiences, but I think we're getting what we need out of it with those item properties. Thanks again!

**Comment by jeffkl** [comment]
Fix is available here: https://github.com/microsoft/MSBuildSdks/releases/tag/Microsoft.Build.NoTargets.2.0.1

**Comment by japj** [comment]
Note that for MSBuild "Restoring" a NoTargets Sdk Project, a TargetFramework property is still required to be set
