### ISSUE TITLE
Restoring traversal project fails in .NET 5 SDK if TargetFrameworks specified

### ISSUE THREAD

**Issue by jeffkl** [microsoft/MSBuildSdks#196]
Some breaking changes in the .NET SDK mean that a previously innocuous property, `TargetFrameworks`, will cause restore to fail.  This is because the property is used to generate two entries in the restore graph but some logic that translates TargetFramework to the expanded TargetFrameworkMoniker property is not imported by Microsoft.Build.Traversal.

We'll need to empty the `TargetFrameworks` property so that NuGet restore doesn't think the project is multi-targeting since Traversal projects don't support multi-targeting anyway.

Repro:

```xml
<Project Sdk="Microsoft.Build.Traversal/2.0.24">
  <PropertyGroup>
    <TargetFrameworks>net45;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="ProjectA\ProjectA.csproj" />
    <ProjectReference Include="ProjectB\ProjectB.csproj" />
  </ItemGroup>
</Project>
```

```cmd
msbuild /t:Restore

Microsoft (R) Build Engine version 16.8.0-preview-20411-05+9a32a8063 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Program Files (x86)\Visual Studio 2019 Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): error : Invalid restore input. Duplicate frameworks found: 'net40, net40'. Input files: \dirs.proj. [dirs.proj]
Build FAILED.

C:\Program Files (x86)\Visual Studio 2019 Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): error : Invalid restore input. Duplicate frameworks found: 'net40, net40'. Input files: \dirs.proj. [dirs.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.72
```

**Comment by abatishchev** [comment]
hi @jeffkl, can you please explain why I cannot override `$(OutputRoot)` so it'd be something like `bin\Release\x64\netcoreapp3.1` what makes more sense to my scenario? this change explicitly erases whatever I set and changes the output to `bin\Release\AnyCPU\net45` what doesn't make sense, I'm building for .NET Core 3.1 using .NET 6 SDK.

**Comment by jeffkl** [comment]
@abatishchev This change only disabled the `TargetFrameworks` property for traversal projects.  Traversal projects don't output anything, they simply tell MSBuild what projects to schedule as part of the build.  Can you elaborate more on what traversal project you have that is causing your issue?

**Comment by abatishchev** [comment]
Spoke to Jeff offline, decided to use https://github.com/microsoft/MSBuildSdks/tree/main/src/NoTargets instead. Thanks!
