### ISSUE TITLE
Visual Studio doesn't handle projects using only Microsoft.Build.NoTargets without "upgrading"

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/MSBuildSdks#20]
**Repro**
Create an empty solution and a project with a sample file using Microsoft.Build.NoTargets
```xml
<!-- test.csproj -->
<Project Sdk="Microsoft.Build.NoTargets">
</Project>
```
```json
{
  "msbuild-sdks": {
    "Microsoft.Build.NoTargets": "1.0.12"
  }
}
```
Attempt to add the project via VS.

**Expected**
VS adds the project and can load it as is

**Actual**
VS show the "One-way upgrade" dialog and changes the project file to this:
```
<Project Sdk="Microsoft.Build.NoTargets" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFrameworkVersion>v2.0</TargetFrameworkVersion>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <UpgradeBackupLocation>
    </UpgradeBackupLocation>
    <OldToolsVersion>2.0</OldToolsVersion>
  </PropertyGroup>
</Project>
```

**Comment by natemcmaster** [comment]
I think that's good enough. Thanks for the guidance!

**Comment by jeffkl** [comment]
I've fixed the SDK but you now have to include the TargetFramework otherwise Visual Studio will attempt to upgrade it.

https://github.com/Microsoft/MSBuildSdks/releases/tag/Microsoft.Build.NoTargets.1.0.26

https://www.nuget.org/packages/Microsoft.Build.NoTargets/1.0.26
