### ISSUE TITLE
Traversal targets FindUnderPath when running Clean

### ISSUE THREAD

**Issue by AlexEyler** [microsoft/MSBuildSdks#205]
I ran into a consistent repro of #35 when I run `dotnet clean`.

```
C:\Program Files\dotnet\sdk\3.1.402\Microsoft.Common.CurrentVersion.targets(5146,5): error MSB4044: The "FindUnderPath" task was not given a value for the required parameter "Path". [C:\Source\BotDesigner\src\all.proj]
```

Repro project:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" Sdk="Microsoft.Build.Traversal/2.1.1">
  <PropertyGroup>
    <IncludeProjects Condition=" '$(IncludeProjects)' == '' ">**\*.csproj</IncludeProjects>
    <TraversalGlobalProperties>
      Configuration=$(Configuration);
      Platform=$(Platform);
      RuntimeIdentifier=$(RuntimeIdentifier)
    </TraversalGlobalProperties>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(IncludeProjects)">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
</Project>
```

I haven't been able to find a version that works yet.

**Comment by AlexEyler** [comment]
Thought I had a fix in 2.0.52 but was mistaken -- not sure which version of the targets has the fix.

**Comment by jeffkl** [comment]
I am unable to repro it.  I've attached a sample that works for me.

[sample.zip](https://github.com/microsoft/MSBuildSdks/files/5293978/sample.zip)

Can you maybe attach a binary log?
```
dotnet clean /bl
```
Attach `msbuild.binlog`.

**Comment by jeffkl** [comment]
Looked at a binlog offline and figured out its because `Platform` is set by `Directory.Build.props` but not `Configuration` which finds a hole in this logic:

https://github.com/microsoft/MSBuildSdks/blob/59125812d15b1e8a45666bb42e381d62c382c022/src/Traversal/Sdk/Sdk.targets#L11-L19

Best workaround is to set `Configuration` as well.

**Comment by AlexEyler** [comment]
Thanks Jeff, the workaround works well for me!

**Comment by jeffkl** [comment]
Closing since there is a workaround
