### ISSUE TITLE
Allow loading .msbuildproj in VS using Traversal

### ISSUE THREAD

**Issue by kzu** [microsoft/MSBuildSdks#206]
Similar to https://github.com/microsoft/MSBuildSdks/issues/97 but for Traversal.

I can back-port #98 if folks think it's worth it. I think it is, brings more consistency with NoTargets too :).

**Comment by jeffkl** [comment]
Sounds like a good improvement, feel free to send a PR!

**Comment by kzu** [comment]
Will do. Thanks!

**Comment by kzu** [comment]
PR sent! 👍
