### ISSUE TITLE
Exclude Implicit references from Microsoft.Build.CentralPackageVersions?

### ISSUE THREAD

**Issue by bording** [Microsoft/MSBuildSdks#21]
Would it be possible to add an option to Microsoft.Build.CentralPackageVersions to exclude the implicit package references from requiring a PackageVersion entry? 

I'd prefer to let those be managed automatically as they currently are, but still have the control that Microsoft.Build.CentralPackageVersions provides for all the other packages.

**Comment by jeffkl** [comment]
Yes I think an new property added to this condition would do:

https://github.com/Microsoft/MSBuildSdks/blob/master/src/CentralPackageVersions/Sdk/Sdk.targets#L92

Feel free to test it out and send a PR

**Comment by bording** [comment]
It looks like it will be a bit more complicated than just adding a condition there, since the implicit references end up getting removed completely by the stuff going on in https://github.com/Microsoft/MSBuildSdks/blob/master/src/CentralPackageVersions/Sdk/Sdk.targets#L28-L54

I see what needs to be done though, so I'll try and get a PR ready soon.

**Comment by bording** [comment]
I did end up spending some time on on this, and got it mostly working, but there were some really weird edge cases that I never go time to work through.

Does #31 still replace the implicit packages? If so, perhaps it will be easier to change that once 2.0 is ready.

**Comment by jeffkl** [comment]
@bording yeah I decided with v2.0 to just ignore implicit package references.  I'll release it today and you can give it a shot.

**Comment by jeffkl** [comment]
Closed via #31
