### ISSUE TITLE
Can we use package reference or GeneratePathProperty to reference managed dlls  c++ cli

### ISSUE THREAD

**Issue by jmecosta** [microsoft/MSBuildSdks#212]
Hi,

trying to organize some of the c++ cli, is it possible to reference c# nugets from there using the CentralPackageVersions either directly or wiht GeneratePathProperty ?

thanks

**Comment by jeffkl** [comment]
`Microsoft.Build.CentralPackageVersions` is just a way to manage your PackageReference versions in one place.

`GeneratePathProperty` allows you to manually consume assets from a NuGet package when the package contains assets that cannot be consumed automatically (like `lib`, `build`, or `contentFiles`).

The C++ project system in Visual Studio does not currently support using `PackageReference`, although NuGet will restore them if you do it from the command-line.

Let me know more about your scenario if that doesn't clear things up.

**Comment by jmecosta** [comment]
thanks @jeffkl 

so basically if i understood your explanation this cant be done in a vcxproj (c++ cli)!

```
<PackageReference Include="Trimble.Technology.ModelViewerCore" />

    <Reference Include="Trimble.Technology.ModelViewerCore.Data.Interop, Version=$(ModelViewerCoreVersion), Culture=neutral, PublicKeyToken=93c0f7e4f1ca9619">
      <HintPath>$(PkgTrimble_Technology_ModelViewerCore)\build\native\bin\$(PlatformTarget)\Trimble.Technology.ModelViewerCore.Data.Interop.dll</HintPath>
      <Private>True</Private>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </Reference>
```

Since the PackageReference  has u mentioned is not supported in vcxproj?

The restore part im not concerned since they are suppose to be restored by other projects that are required before to be build

thanks

**Comment by jeffkl** [comment]
Correct that isn't technically supported because in Visual Studio the PackageReference is ignored and packages aren't restored.  It will work if you restore from the command-line before you try to build in Visual Studio.

The supported way to do this is with `packages.config`.  This method restores packages into a folder relative to your project so you can do something like:

```xml
<Reference Include="Trimble.Technology.ModelViewerCore.Data.Interop, Version=$(ModelViewerCoreVersion), Culture=neutral, PublicKeyToken=93c0f7e4f1ca9619">
 
 <HintPath>..\..\packages\Trimble.Technology.ModelViewerCore.$(ModelViewerCoreVersion)\build\native\bin\$(PlatformTarget)\Trimble.Technology.ModelViewerCore.Data.Interop.dll</HintPath>
  <Private>True</Private>
  <EmbedInteropTypes>False</EmbedInteropTypes>
</Reference>
```

The drawback of `packages.config` is the version can't be managed in one place.  So if you have 100 `.vcxproj` projects with 100 `packages.config`, you'll have to manage the versions of your packages in 100 files.

**Comment by jmecosta** [comment]
yeah, also another problem is i will duplicate packages in that folder and in cache which i want to solve... 

ok... so basically because we dont have many like those what i will do is deploy the needed dlls into the builddrop folders and reference from there...

thanks for the help... i would be great if at least c++ cli would be support to avoid this cumbersome setup :(
