### ISSUE TITLE
[Question] Custom SDK doesn't show under 'Dependencies -> SDK' node in VS

### ISSUE THREAD

**Issue by DoCode** [Microsoft/MSBuildSdks#24]
Is this the correct behavior that a custom SDK, like `NoTargets` doesn't show under the `Dependencies -> SDK` node in Visual Studio?

Perhaps two points I see:

1) When using a custom SDK and define this like the project XML tag like
```xml
<Project Sdk="MyCompany.MyProduct.SDK/2018.1.0-preview3">
...
```
then we cannot display and update the SDK inside Visual Studio and the NuGet Package Manager. Both don't see and detect the custom SDK.

2. When using a custom SDK and define it with
```xml
...
<ItemGroup>
  <PackageReference Include="MyCompany.MyProduct.SDK" Version="2018.1.0-preview3" PrivateAssets="All" />
</ItemGroup>
...
```
then it be displayed and is updateable from NuGet Package Manager inside Visual Studio.

**Comment by jeffkl** [comment]
I think you should move this to https://github.com/dotnet/project-system/issues as that is the probably where the fix would go.  This repository only contains the actual SDKs and not the MSBuild or Visual Studio implementation of how they are used.

**Comment by jeffkl** [comment]
I'm closing this in favor of https://github.com/dotnet/project-system/issues/3463
