### ISSUE TITLE
Warning when importing CentralPackageVersions from Directory.Build.props

### ISSUE THREAD

**Issue by aaronla-ms** [microsoft/MSBuildSdks#249]
When importing the "Microsoft.Build.CentralPackageVersions" package as recommended in the readme, but placing it into directory.build.props rather than importing directly within each project, build fails with a warning message:

> aaronla@aaronla-rabbit:repro-cpv-warning-dbp$ dotnet build -nologo
> y:\ObpNugetCache\microsoft.build.centralpackageversions\2.0.1\Sdk\Sdk.props(14,3): warning MSB4011: "C:\Program Files\dotnet\sdk\3.1.409\Current\Microsoft.Common.props" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\3.1.409\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props (40,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\repos\aaronla-ms\bug-repros\repro-cpv-warning-dbp\repro-cpv-warning-dbp.csproj]

Repro: https://github.com/aaronla-ms/bug-repros/tree/main/repro-cpv-warning-dbp

**Comment by dfederm** [comment]
Seems like a bug in `Microsoft.Common.props`. It doesn't set  `MicrosoftCommonPropsHasBeenImported` until *after* it imports `Directory.Build.props`, so `Directory.Build.props` (and downstream imports) can't rely on `MicrosoftCommonPropsHasBeenImported` being set.

@JeffKl, do you know why CentralPackageVersions imports the common props at all? It doesn't seem to import the common targets, so I'm not sure why it's import the common props.

**Comment by dfederm** [comment]
@aaronla-ms I'd also strongly discourage you from using this SDK in Directory.Build.props anyway. The `Sdk` element imports the props and targets of the Sdk at the top and bottom of the file it's in, so in this case the Sdk's props would be imported at the top of Directory.Build.props, and the Sdk's targets would be imported at the bottom of Directory.Build.props.

Based on that, I actually would guess that this doesn't even work at all functionally regardless of the warning. Specifically, the Sdk's targets import the Packages.props which updates any PackageReferences, and no PackageReferences would have been present this early in evaluation yet. So the Sdk just wouldn't even work in this scenario irrespective of the warning.

**Comment by aaronla-ms** [comment]
@dfederm I hear ya, and I wasn't too happy about using Sdk in this manner either, but it's the best I could come up with.

Do you have any proposals for alternatives?

**Comment by dfederm** [comment]
Put it in `Directory.Build.targets`

**Comment by aaronla-ms** [comment]
Thanks for clarification offline. Putting CPV in Directory.Build.targets seems like a fine alternative. I'll mark this issue closed with that guidance.
