### ISSUE TITLE
dotnet restore doesn't download Microsoft.Build.NoTargets nuget package

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/MSBuildSdks#25]
```xml
<Project Sdk="Microsoft.Build.NoTargets">
  <PropertyGroup>
   <!-- 
      Any target framework you want as long as its compatible 
      with your referenced NuGet packages
     -->
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  
  <Target Name="HelloWorld" AfterTargets="Build">
    <Message Text="Hello World" Importance="High" />
  </Target>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.NoTargets" />
  </ItemGroup>

</Project>
```
I have this project file, and when I run `dotnet restore` (version 15.5.0-preview-007044) I get the following error... am I misunderstanding how this ties together with Nuget?

detailed error

```
Build started 4/11/2018 5:01:52 PM.
     1>Project "D:\tmp\source\dotnetapp\empty.tsproj" on node 1 (Restore target(s)).
     1>Building with tools version "15.0".
     1>D:\tmp\source\dotnetapp\empty.tsproj : error MSB4236: The SDK 'Microsoft.Build.NoTargets' specified could not be found.
     1>Done Building Project "D:\tmp\source\dotnetapp\empty.tsproj" (Restore target(s)) -- FAILED.

Build FAILED.

       "D:\tmp\source\dotnetapp\empty.tsproj" (Restore target) (1) ->
         D:\tmp\source\dotnetapp\empty.tsproj : error MSB4236: The SDK 'Microsoft.Build.NoTargets' specified could not be found.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.06
```

**Comment by jeffkl** [comment]
You must have MSBuild 15.6+. Please try a newer .NET Core.

**Comment by paulvanbrenk** [comment]
Now my question is.. how do I update? I assumed that would come with VS (running both 15.6 and 15.7 preview).

**Comment by paulvanbrenk** [comment]
Uninstalled the old 15.5 SKD, but I see the same behavior with `2.1.200-preview-007517`

**Comment by bording** [comment]
@paulvanbrenk Do you have the version of the Microsoft.Build.NoTargets SDK defined anywhere? You need to reference the version for the NuGet resolver to kick in.

See https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk

**Comment by binki** [comment]
I would expect the docs page on https://github.com/microsoft/MSBuildSdks/tree/master/src/NoTargets to actually show this in its example. Instead it just shows the Sdk without the version suffix.
