### ISSUE TITLE
Support for Conditional Target Framework

### ISSUE THREAD

**Issue by netxph** [microsoft/MSBuildSdks#251]
I'm looking to centralize package versions with Target Framework conditions. I can't find anything in documentation and when I tried the following in `Packages.props` below, it doesn't work. Am I missing something?

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
</ItemGroup>
```

```xml
<Choose>
   <When Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
      <ItemGroup>
      <ItemGroup>
   </When>
</Choose>
```

```xml
<PackageReference 
   Update="Microsoft.Extensions.Logging" 
   Condition=" '$(TargetFramework)' == 'netstandard2.0' " 
   Version="3.1.2" />
```

```xml
<ItemGroup Condition="$(DefineConstants.Contains('NETSTANDARD'))">
</ItemGroup>
```

There are certain libraries like in our case `SecureBlackBox` that requires different package depending on the target framework.

* NETFRAMEWORK - `SecureBlackBox`
* NETCOREAPP - `SecureBlackBox.NetCore`

**Comment by jeffkl** [comment]
If you can use two _different_ packages for the target frameworks, you'll want to just have a simple `<PackageReference Update="" />` in your `Packages.props`.

If you really need two different versions of a package based on target framework, then your example above should work just fin:
```xml
<PackageReference 
   Update="Microsoft.Extensions.Logging" 
   Condition=" '$(TargetFramework)' == 'netstandard2.0' " 
   Version="3.1.2" />

<PackageReference 
   Update="Microsoft.Extensions.Logging" 
   Condition=" '$(TargetFramework)' != 'netstandard2.0' " 
   Version="4.0.0" />
```

There's no special magic to `Packages.props`, whatever properties are available can be used for conditions.  Its just a standard MSBuild file.

**Comment by Paulskit** [comment]
I face the same issue as well.

**Directory.Build.props**
```xml
<Project>
    <PropertyGroup>
        <TargetFrameworks>netcoreapp3.1;net6.0</TargetFrameworks>
    </PropertyGroup>
</Project>
```

**Packages.props**
```xml
<Project>
    <ItemGroup>
        <PackageReference Condition="'$(TargetFramework)' == 'netcoreapp3.1'" Update="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.20" />
        <PackageReference Condition="'$(TargetFramework)' == 'net6.0'" Update="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    </ItemGroup>
</Project>
```

Visual Studio shows them correctly:
![image](https://user-images.githubusercontent.com/9947675/141147076-af67de88-a9a9-45a9-a1bc-e8f38d47e7a8.png)

But is unable to build:
![image](https://user-images.githubusercontent.com/9947675/141147136-4024b224-93f1-4fb7-a331-e56d18d0413d.png)

**Comment by jeffkl** [comment]
I think the best solution is to declare a property and use conditions to set the version based on the target framework.  This is an example:

https://github.com/microsoft/slngen/blob/b47590826ca2116e4818e867add9cf431860e658/Packages.props#L8-L11
