### ISSUE TITLE
Change `obj` folder output when using Microsoft.Build.Traversal

### ISSUE THREAD

**Issue by craigktreasure** [microsoft/MSBuildSdks#258]
I have a project that changes the output paths of everything to a common set of output folders. The new locations are all configured in a `Directory.Build.props` at the root of the repository and the projects all emit their outputs to the right locations. 

For example:

```
/dirs.proj
/src/dirs.proj
/src/MyProject/Myproject.csproj
/test/dirs.proj
/test/MyProject.Tests/MyProject.Tests.csproj
```

`/dirs.proj`:

```xml
<Project Sdk="Microsoft.Build.Traversal">
  <ItemGroup>
    <ProjectReference Include="src/dirs.proj" />
    <ProjectReference Include="test/dirs.proj" />
  </ItemGroup>
</Project>
```

`/src/dirs.proj` and `/test/dirs.proj`:

```xml
<Project Sdk="Microsoft.Build.Traversal">
  <ItemGroup>
    <ProjectReference Include="**/*.*proj" />
  </ItemGroup>
</Project>
```

After introducing `dirs.proj` with `Microsoft.Build.Traversal`, I now get `obj` folders created alongside the `dirs.proj` files. They appear to come from NuGet package restoration.

Example output after a restore:

```
/__output/...
/__intermediate/...
/dirs.proj
/obj/...
/src/dirs.proj
/src/obj/...
/src/MyProject/Myproject.csproj
/test/dirs.proj
/test/obj/...
/test/MyProject.Tests/MyProject.Tests.csproj
```

Is it possible to make the output of the Traversal projects respect the paths defined in `Directory.Build.props` or to omit the `obj` folders entirely?

**Comment by dfederm** [comment]
NuGet generates its assets during restore to `$(MSBuildProjectExtensionsPath)`, so you'll want to redirect that property to place the files somewhere else.

**Comment by craigktreasure** [comment]
So, it seems the `MSBuildProjectExtensionsPath` property is typically derived from `BaseIntermediateOutputPath`, which I am configuring in `Directory.Build.props`. I'm thinking that either my properties from `Directory.Build.props` are getting set too late or they're getting stomped.

**Comment by craigktreasure** [comment]
I believe my properties are getting stomped at some point, but I haven't been able to determine when. I'm still learning to wield [MSBuild Binary and Structured Log Viewer](https://msbuildlog.com/). My properties are all getting set, but a few key properties have been reset. I've worked around the issue by setting `CustomAfterTraversalProps` in `Directory.Build.props`, which points to a props file that simply re-sets the `BaseIntermediateOutputPath` and `MSBuildProjectExtensionsPath` back to my intended values and includes the project name.

This results in the following:
```
/__output/...
/__intermediate/dirs/...
/__intermediate/src/dirs...
/__intermediate/test/dirs...
/dirs.proj
/src/dirs.proj
/src/MyProject/MyProject.csproj
/test/dirs.proj
/test/MyProject.Tests/MyProject.Tests.csproj
```

My suspicion is Traversal's manual import of `Sdk.props` from `Microsoft.NET.Sdk` is causing things to be reset, but i'm happy to be proven wrong.

**Comment by dfederm** [comment]
Do you have a minimal repro to look at?

Setting `MSBuildProjectExtensionsPath` in `Directory.Build.props` should be early enough. I've seen it work in some repos when set there.

**Comment by craigktreasure** [comment]
I'll put one together and send it over.

**Comment by craigktreasure** [comment]
Doh! That was a good exercise. Turns out we had guarded some or our properties for a `csproj`. My bad. We're good. Thanks for the **Preprocess** suggestion. That was a great tip!
