### ISSUE TITLE
Location of third party SDK 

### ISSUE THREAD

**Issue by dotChris90** [Microsoft/MSBuildSdks#26]
Hello MSBuild Team, 

not sure if i am right here but - I read about your SDK System and was curious if there are any tutorials and so on for writing own Sdks. 

Until now I just found out that MSBuild Looks for Sdks in Folder where dotnet.exe is located. 
I saw how other Sdks are made and followed them. So was able to create a Sdk.props and Targets file and it worked - very nice and easy to understand. BUT! 

The dotnet Folder require admin rights - so are there other Locations it will check? 
Before was thinking maybe it checking my ".nuget" Folder but seems it does not. 

Thanks for your time and very good work! :D your SDK System is really something makes MSBuild more easy.

**Comment by dotChris90** [comment]
Close because got anwser from Microsoft docs. Nuget resolver and global.json were keywords i was looking. ;)

**Comment by Nirmal4G** [comment]
1. [MSBuild-SDKs by Me](https://github.com/nirin/msbuild-sdks)
2. [MSBuildSdks by @Microsoft](https://github.com/Microsoft/MSBuildSdks)
3. [MSBuildSdkExtras by @onovotny](https://github.com/onovotny/MSBuildSdkExtras)
