### ISSUE TITLE
Microsoft.Build.CentralPackageVersions or ManagePackageVersionsCentrally

### ISSUE THREAD

**Issue by avivanoff** [microsoft/MSBuildSdks#269]
What is the recommended way going forward for managing NuGet packages centrally: Microsoft.Build.CentralPackageVersions or [ManagePackageVersionsCentrally](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions)?

**Comment by bormm** [comment]
My understanding is that ManagePackageVersionsCentrally is a preview integrated feature that was created based Microsoft.Build.CentralPackageVersions ? So it will be the future, but its still preview.
Personally I like the way how these SDK packages are working and also a fan of modular components. So I do not understand why this will now be a integral part of nuget. I do not see any usability or technical benefit, only reduced modularity.

**Comment by CZEMacLeod** [comment]
@bormm I think the idea of integrating the functionality is mainly to make the nuget package manager UI, command line and package manage console understand how to work with the Directory.Packages.props file and not inject version numbers in the wrong place. However, I don't see any of that in the nuget preview, and it seems to be something that has been dropped from being actively worked on.

**Comment by jeffkl** [comment]
The official recommendation is to use `Microsoft.Build.CentralPackageVersions` until NuGet ships their in-box implementation of central package version management as production ready.
