### ISSUE TITLE
Why does Microsoft.Build.NoTargets need.... a TargetFramework?

### ISSUE THREAD

**Issue by jzabroski** [microsoft/MSBuildSdks#271]
Forgive me if there is an FAQ and I missed it, but... it seems strange to me that an Sdk called NoTargets requires a framework identifier.

Is the reason that a given Sdk could have multiple implementations depending on the target framework?

Sample csproj:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.Build.NoTargets/3.0.4">
  <!-- ReSharper disable UnknownProperty -->
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework> <!-- WHY IS THIS NEEDED -->
    <AssemblyTitle>RiskyBusiness</AssemblyTitle>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <BuildPackage>true</BuildPackage>
    <PackageVersion>0.0.0.1-dev</PackageVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NuspecFile>package.nuspec</NuspecFile>
    <NuspecProperties>version=$(PackageVersion);id=$(AssemblyTitle);description=$(AssemblyTitle);authors=$(Company);copyright=$(Copyright)</NuspecProperties>
    <NoWarn>NU5100,NU5110,NU5111</NoWarn>
  </PropertyGroup>
</Project>
```

Output:
```
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.301\NuGet.targets(131,5): error : Invalid framework identifier ''. [D:\Users\John.Zabroski\source\infrastructure2\trunk\RiskyBusiness.sln]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.301\NuGet.targets(131,5): error : Invalid framework identifier ''. [D:\Users\John.Zabroski\source\infrastructure2\trunk\RiskyBusiness.sln]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:20.48
```

**Comment by jeffkl** [comment]
Building projects from the command-line do not require a target framework.  But to load projects in Visual Studio using the CSPROJ project system, this property is required.  We could try defaulting it in the SDK but last time I tested that (over a year ago), the project system didn't like it.  Being able to load the project in Visual Studio is very useful so we have the requirement.

**Comment by jzabroski** [comment]
@jeffkl Thanks - I also notice that if you temporarily delete the TargetFramework from Visual Studio, Visual Studio gets very slow and angry.  Only solution once it gets angry seems to be to restart Visual Studio.
