### ISSUE TITLE
Add a parallel PkgVersion_PACKAGE_NAME variable for when PackageReference Version="*"

### ISSUE THREAD

**Issue by jzabroski** [microsoft/MSBuildSdks#272]
> Use the [GeneratePathProperty](https://github.com/NuGet/NuGet.Client/pull/2271) feature I added:
> 
> https://blog.dangl.me/archive/accessing-nuget-package-paths-in-your-net-sdk-based-csproj-files/
> 
> _Originally posted by @jeffkl in > https://github.com/microsoft/MSBuildSdks/issues/132#issuecomment-536605034_

@jeffkl 

First off, this was a great feature you added.   I am using it a ton.

One interesting use I have for it is to transclude one package inside of another (wrapper nuget package).  In this scenario, I always want to transclude the latest dependency via Verison="*", so I don't actually know the Package Version.  It seems a bit kludgey to get the actual version via calls to MSBuild property functions.

On the other hand, I understand that "*" is a bit of an edge case and so I can see why you implemented it this way vs. other ways, since getting the path to the package from the central store allows people to invoke binaries contained in the package, even if they're not .NET CLI Tools.

Thoughts?

**Comment by jeffkl** [comment]
Generally speaking, wildcard versions in NuGet are a bad practice.  If you don't specify a version then NuGet will contact the feed constantly and you lose caching.  For large restores this can cause major slowness.  You can also alter a feed list or delete a package to make your build non-deterministic.  So in my opinion we should not make it "easier" to use wildcard versions, if I got a vote, I would say the wildcard version should go away. 😄 

But if enough people want a feature then the majority wins.  I think this issue should be moved to NuGet as well?

**Comment by jzabroski** [comment]
> Generally speaking, wildcard versions in NuGet are a bad practice. If you don't specify a version then NuGet will contact the feed constantly and you lose caching. For large restores this can cause major slowness. You can also alter a feed list or delete a package to make your build non-deterministic.

I agree that safety is a priority, and you call out several safety issues while not addressing the one I was thinking of.

It seems a lot safer to expose a way to get the version rather than having me scrape it, e.g.:

```xml
<PropertyGroup>
  <PkgVersionPACKAGE_NAME>$([System.IO.Path]::GetFileName($(PkgPACKAGE_NAME)))</PkgVersionPACKAGE_NAME>
</PropertyGroup>
```

The above assumes a particular directory hierarchy for packages that could break in the future.

It is also not about making it easier to use wildcard versions.  Rather, it makes it easier to refer to the version in a way that doesn't interfere with Visual Studio Package Manager.  Visual Studio Package Manager doesn't understand MSBuild Property values inside the Version attribute.  So, while it could be parameterized, you lose Visual Studio Package Manager functionality.

If this is purely about work prioritization, I can add this myself by following your previous two PRs for supporting this in the MSBuildSdks and the .NET SDK for the Common Project System.

Background Noise: Separately, I do think the behavior for Version="*" is slightly broken.  I don't think the csproj should change if someone runs the following if ExampleProject.csproj contains `<PackageReference Include="Example.Package" Version="*"/>` since * is by definition the very latest:

```
dotnet.exe add .\ExampleProject.csproj package  Example.Package
```

https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli#update-a-package

**Comment by jeffkl** [comment]
Closing for now as this would need to be a feature in NuGet, feel free to open an issue there for discussion

**Comment by jzabroski** [comment]
I am fine with closing this.  My workaround was to set the package version via build parameter, and make sure I use that value consistently across the application.  It works pretty well.

e.g., in case anyone finds this helpful:

```xml
  <ItemGroup>
    <PackageReference Include="DatabaseMigrationTool" Version="$(MyAppPackageVersion)" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageBinDirectoryContents Include="$(PkgDatabaseMigrationTool)\**" />
  </ItemGroup>

  <ItemGroup>
    <!-- This is a dummy MSBuild Item to work-around the fact MSBuild passes Nuget a collection of files to pack. -->
    <!-- If there is not at least one file to pack, Nuget will throw an
         error NU5017: Cannot create a package that has no dependencies nor content. -->
    <None Update="Workaround.ReadMe.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Copy the files to the output directory -->
  <Target Name="CopyPackageDirectoryFiles" AfterTargets="Build">
    <Message Importance="High" Text="%24(PkgDatabaseMigrationTool) [$(PkgDatabaseMigrationTool)]" />

    <Copy SourceFiles="@(PackageBinDirectoryContents)" DestinationFiles="@(PackageBinDirectoryContents->'$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
```

**Comment by jeffkl** [comment]
Great, glad you found a workaround!  That looks like a good way to solve the issue in my opinion.
