### ISSUE TITLE
Cannot use NuGet targets with explicit Imports

### ISSUE THREAD

**Issue by wsheemsft** [microsoft/MSBuildSdks#275]
We have a need to add custom targets in a project using Microsoft.Build.NoTargets. The bug is that NuGet SDKs, such as NoTargets, do not seem to work with the explicit import of `Sdk.props` and `Sdk.targets`.

I am using dotnet 6.0.100-preview.5.21302.13

For the following repros, put the XML in `whatever.csproj` and run `dotnet build whatever.csproj`.

This works:

```xml
<Project Sdk="Microsoft.Build.NoTargets/1.0.40">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
  <Target Name="SayHello" BeforeTargets="AfterBuild">
    <Message Importance="High" Text="If you see this it works" />
  </Target>
</Project>
```

```
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Working ->
  If you see this it works

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.95
```

This does not:

```xml
<Project>
  <!-- Format taken from https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk -->
  <!-- This also fails: <Import Project="Sdk.props" Sdk="Microsoft.Build.NoTargets" /> -->
  <Import Project="Sdk.props" Sdk="Microsoft.Build.NoTargets/1.0.40" />
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
  <Target Name="SayHello" BeforeTargets="AfterBuild">
    <Message Importance="High" Text="If you see this it works" />
  </Target>
  <Import Project="Sdk.targets" Sdk="Microsoft.Build.NoTargets/1.0.40" />
</Project>
```

```
...\NotWorking.csproj(4,33): error MSB4236: The SDK 'Microsoft.Build.NoTargets/1.0.40' specified could not be found.

Build FAILED.

...\NotWorking.csproj(4,33): error MSB4236: The SDK 'Microsoft.Build.NoTargets/1.0.40' specified could not be found.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.07
```

I can see via Process Monitor that the working case is correctly using the NuGet SDK resolver and is looking in my common user NuGet packages folder. The non-working case seems to only be looking in the official SDK folder; the NuGet packages folder is never considered.

**Comment by wsheemsft** [comment]
I just found that this works if I use this syntax:

```xml
<!-- No version specified -->
<Import Project="Sdk.props" Sdk="Microsoft.Build.NoTargets" />
```

and set the version in `global.json`:

```json
{
    "msbuild-sdks": {
        "Microsoft.Build.NoTargets": "1.0.40"
    }
}
```

While this can unblock us, I still expect the original syntax to work.

**Comment by jeffkl** [comment]
When using an `<Import />` element, you can't use the `SDK/version` syntax, as that only works for the top-level `<Project Sdk="name/version" />` element.

https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019#reference-a-project-sdk

So for `<Import />` you need to use it like this:

```xml
<Import Project="Sdk.props" Sdk="Microsoft.Build.NoTargets" Version="1.0.40" />
```

Or you can use `global.json` which allows you to control the version in a single place which is highly recommended for `NoTargets` anyway in case you have more than one project in your tree.

**Comment by wsheemsft** [comment]
Thanks, I missed the explicit version syntax at the bottom of that article. It works!
