### ISSUE TITLE
Microsoft.Build.NoTargets creates outupt directories

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/MSBuildSdks#278]
I created a new C# SDK solution and modified the .csproj to be

`<Project Sdk="Microsoft.Build.NoTargets/3.1.0">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>
</Project>`

I noticed that when I build an obj and a bin directory are still created. They contain various file including a obj\Debug\net6.0\ClassLibrary5.AssemblyInfo.cs. Note that nothing actually gets built as expected.
Is this expected, if I'm not building anything why create these directories and files?

**Comment by jeffkl** [comment]
I would expect the `obj` folder to be there as part of NuGet restore, but not really `bin`.  The AssemblyInfo source file generation could definitely be disabled.  Can you paste the contents of these folders so we can determine what should be there and what shouldn't be?

Do a restore and build on Windows then run `tree /f obj` and `tree /f bin` from the project folder and copy/paste the output.

**Comment by davidhunter22** [comment]
I'm a bit confused by your comment "I would expect the obj folder to be there as part of NuGet restore". If I have an empty NoTargets project it has no package dependencies so why would NuGet package restore. Does Nuget package restore not have a "nothing to do here" check before it starts creating things?

**Comment by jeffkl** [comment]
Okay it looks like we can get rid of:

* `obj\Debug\net6.0\ClassLibrary5.AssemblyInfo.cs`
* `obj\Debug\net6.0\ClassLibrary5.AssemblyInfoInputs.cache`

By setting `GenerateAssemblyInfo` to `false`

We can get rid of:

* `obj\Debug\net6.0\ClassLibrary5.csproj.FileListAbsolute.txt`
* `obj\Debug\net6.0\ClassLibrary5.GeneratedMSBuildEditorConfig.editorconfig`

By setting `GenerateMSBuildEditorConfigFile` to `false`

The following files are written by NuGet during restore even if your project references no packages and I'm not aware of a way to disable it:
```
obj
│   ClassLibrary5.csproj.nuget.dgspec.json
│   ClassLibrary5.csproj.nuget.g.props
│   ClassLibrary5.csproj.nuget.g.targets
│   project.assets.json
│   project.nuget.cache
│
└───Debug
    └───net6.0
            ClassLibrary5.assets.cache
```

And the `bin` folder is created just in case its needed and I don't see a good way to turn it off (and builds could fail if a user copied something there expecting it to exist).

https://github.com/dotnet/msbuild/blob/b0bb46ab87d41082b409cd2c61546504d7e6c845/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1164-L1166
