### ISSUE TITLE
How to publish projects in separate folder using MSBuild and Microsoft.Build.Traversal

### ISSUE THREAD

**Issue by denjmpr** [microsoft/MSBuildSdks#290]
Hi,

I want to use Microsoft.Build.Traversal sdk to publish referenced projects to separate folders using msbuild from command line.
Could you help?
## Minimal Reproduction Scenario
1. Unzip attached sample:
[Publish.zip](https://github.com/microsoft/MSBuildSdks/files/7090707/Publish.zip)
2. Open "Developer Command Prompt for VS 2019";
3. Navigate to the sample root with cd command with "Developer Command Prompt for VS 2019";
4. Execude such command from "Developer Command Prompt for VS 2019":
`msbuild Publish.csproj /t:restore;publish /p:RunCodeAnalysis=false /clp:ErrorsOnly /p:Configuration=Release /p:OutputPath=C:\OutputFolder`
5. Observe: all files inside C:\OutputFolder.
## Expected Behavior
I want that files related to **WinFormsApp1.csproj** appears in **C:\OutputFolder\WinFormsApp1** folder and files related to **WinFormsApp2.csproj** appears in **C:\OutputFolder\WinFormsApp2** folder.
Could it be achieved **without projects modification** but by modifying command line command?

**Comment by jeffkl** [comment]
At this time, Microsoft.Build.Traversal just schedules builds in dependency order.  The location of where outputs are placed _should_ be declared by projects themselves and not as a global property.  Placing all outputs in the same folder could lead to non-deterministic behavior as assemblies of different versions can be written over causing runtime issues.

Controlling where outputs go is part of the .NET SDK and not really something that Traversal handles.  I would suggest opening an issue at https://github.com/dotnet/sdk/ instead
