### ISSUE TITLE
[BuildTraversal] Usage of ProjectReference vs Reference

### ISSUE THREAD

**Issue by Stefan75** [microsoft/MSBuildSdks#292]
Hello,

I have some questions related to traversal builds.

I have searched for documentation, but nothing I have found has helped, hence this issue.

Introduction:
- Currently we have several solution files, each of them containing 
  a. ProjectReferences for projects inside of the same solution
  b. Refernces for projects outside of the solution
  
- We have a cmake based custom build system where the different solutions are merged and a global dependency graph is created.  Based on this a global build order is defined.

Now I have read something about the Traversal Build SDK, which raises some questions for me:
- If I want to use traversal builds, I guess I must only use ProjectReferences.
     (so that msbuild is able to create a dependency graph to derive the build order)
     Is this true?

- If I want to use visual studio I still would use solution files, correct?

- If I want to use multiple solution files, some ProjectReferences inside of the project files  would refer projects outside of a solution.
  (AFAIK visual studio does not support adding such project references via UI, but I would be able to create them manually.)
    
  Is this the right way to do?
  Is this a problem?

With best regards,
stefan

**Comment by jeffkl** [comment]
These are excellent questions.  Let me try and answer them all and please ask more if I don't answer them well enough.

> If I want to use traversal builds, I guess I must only use ProjectReferences.

Yes that is correct, `ProjectReference` items are used to determine build dependency ordering and is the only item type you can use.  This is similar to projects themselves.

> If I want to use visual studio I still would use solution files, correct?

This is sort of correct.  Visual Studio 2017 or higher does support opening a folder but does not provide the best experience.  If you want everything to work really well, a solution file is required for Visual Studio to load your projects.

> If I want to use multiple solution files, some ProjectReferences inside of the project files would refer projects outside of a solution.

Yes, Visual Studio won't build your loaded projects if they depend on an unloaded project that hasn't been built previously from the command-line.  Its a terrible user experience.

> Is this the right way to do?

There is a better way and is what I highly recommend for large codebases.  Try out the following and see if it works for you:
1. Create a `dirs.proj` in every folder of your tree that doesn't already contain a project to point to all projects you want built if you could build that "folder".
2. Add `.sln` to your `.gitignore` so Visual Studio solution files are not checked in
3. Adopt [SlnGen](https://github.com/microsoft/slngen/) to generate solutions on the fly

This allows you to go to any folder which will have a `dirs.proj` or an actual project, run `slngen` and load that set of projects and their transitive dependencies in Visual Studio.

There's definitely a threshold of total project count where Traversal projects don't make sense.  In my experience once you get over around 40 projects and 5 developers, Visual Studio solution files just don't scale.

**Comment by Stefan75** [comment]
Thanks for your reply.

If I understand you correctly, with the help of SlnGen I would generate dynamically solutions. 
The tools ensures that all required projects are part of the solution so that visual studio works well.
In this case, required is defined by all direct and indirect ProjectReferences. 

Thanks, I will think about it and maybe I will prototype it.

> Yes, Visual Studio won't build your loaded projects if they depend on an unloaded project that hasn't been built previously > from the command-line. Its a terrible user experience.

Does this mean that Visual Studio simply assumes that the developer has already ensured that all targets of external ProjectReferences exist?
It sounds like Visual Studio *processes* referenced projects outside of solutions like dll references.
Is this correct?

With the help of SlnGen it would be possible to bootstrap with visual studio. 


Our code base is a little bit bigger:
- I guess we have more than 1500 cs project files, distributed over more than 100 solution files
  (and a lot of other target)
- We typically download the drop output of our central build to our developer machines. Then we work with visual studio and solution files.  All projects inside of the solution can be build with visual studio.
  (the other targets just exists because we have downloaded all targets)

The other solution would be to convert project files.
If all archived project files would be valid for visual studio (only ProjectReferences inside of the solution),
then a tool could create project files where all *known* References are converted to ProjectReferences (e.g. for a central build).

Is there any difference related to this topic if the project files are using the new sdk-style or not?
Is there any difference related to this topic if the targets are .NET Framework or .NET >= 5 targets (or even managed C++)?

Thank you in advance,
stefan

**Comment by jeffkl** [comment]
> If I understand you correctly, with the help of SlnGen I would generate dynamically solutions.
> The tools ensures that all required projects are part of the solution so that visual studio works well.
> In this case, required is defined by all direct and indirect ProjectReferences.

Yes that is correct, SlnGen walks the dependency tree and adds all transitive project references to the generated solution.

> Does this mean that Visual Studio simply assumes that the developer has already ensured that all targets of external ProjectReferences exist?

Basically yes, Visual Studio looks for the output of a project and if its there it assumes it was built somewhere else.  I don't think its a good user experience to train developers to build from the command-line before building in Visual Studio though so I don't recommend it.

Solution files don't contain any build logic and are only pointers used by Visual Studio to know what projects to load.  I would look into not having any solutions in your repository at all and letting developers generate them on-the-fly for the cone of projects they want to work on.  SlnGen lets you specify multiple projects if you want to create a solution for a bigger set or you can just run it against a unit test project and get that project plus all of the dependencies which probably has the code you want to work on.  Internally at Microsoft, we have lots of repos with hundreds of projects and dozens of developers but we don't have a single Visual Studio solution file in there.  The workflow is from the command-line you go to the "folder" you want to work on and run `slngen` to load it in Visual Studio.

I'm also working on a Visual Studio extension that generates solutions on the fly with the idea being that you double-click on a project and Visual Studio opens it with all of its dependencies (as opposed to the current logic to only open that one project).

> Is there any difference related to this topic if the project files are using the new sdk-style or not?
> Is there any difference related to this topic if the targets are .NET Framework or .NET >= 5 targets (or even managed C++)?

It does not matter what projects you reference in a Traversal project.  SlnGen will add them all to the solution unless you tell it not to.  This would be useful if you have a random project in your tree that you want built but it won't actually load in Visual Studio.

**Comment by Stefan75** [comment]
> Internally at Microsoft, we have lots of repos with hundreds of projects and dozens of developers but we don't have a single Visual Studio solution file in there. The workflow is from the command-line you go to the "folder" you want to work on and run slngen to load it in Visual Studio.

In such cases (without solution file) how do you centrally build "all" ?
Are you using the "Traversal Build SDK" ?
(also with repos with more than 1000 projects?)

**Comment by jeffkl** [comment]
> In such cases (without solution file) how do you centrally build "all" ?

There is always a Traversal project at the root that points to direct subfolders, and each subfolder has another Traversal project until eventually a Traversal project points to a real project.  

> Are you using the "Traversal Build SDK" ? (also with repos with more than 1000 projects?)

Yes that's what is used internally to build entire repositories.  One repository has ~3,000 projects with this method, lots of others have just under 1,000.

**Comment by Stefan75** [comment]
We started to use solution-filter files (slnf files). Maybe this could be used too.

Is there a difference between
a. using solution filter files and unload projects which are currently not of interest and
b. using solutions with project-references to *external* projects outside of the solution ?

If the created solutions of SlnGen are too big, maybe as solution filter would be of help.

This could even be a nice feature for SlnGen:
Input: Desired Projects,
Output: A solution with all traversal dependencies and next to it a solution filter file with just the desired projects enabled.

**Comment by jeffkl** [comment]
As far as I know, solution filters are only useful if you have a big solution file that contains everything.  When you have hundreds of projects and you're adding new projects occasionally, that means you're update the solution file and any solution filter that needs it.  The maintenance of all this is too high once you hit a certain project count or contributor count in my opinion.

If you have 50 projects, a few developers, and almost never add new projects, then maintaining a solution file and a few solution filters is not that bad.  But if you are adding new projects occasionally or you have dozens of developers, then generating solutions on the fly is better.  The more developers, the more likely they want to work on different parts of the code so maintaining all of those solution filters can be a pain and if you're adding projects occasionally, then updating the main solution and every solution filter is also not fun.

But again, this is entirely subjective.  My opinion is that at a certain threshold, solution generation is best.  But my threshold might be different than yours.  The nice thing here is you have options!
1. Use one big solution, no solution filters
2. Use one big solution, multiple solution filters
3. Use Traversal projects, generate solutions on the fly
4. Any combination of the above


> This could even be a nice feature for SlnGen:
> Input: Desired Projects,
> Output: A solution with all traversal dependencies and next to it a solution filter file with just the desired projects enabled.

Since the design of SlnGen at the moment is to only generate a solution to load projects in Visual Studio and never merge them, then generating a solution filter isn't really needed.  If you want to change the cone of projects, you simply regenerate the solution file.  If we changed the design to have these solutions merged, then we could reconsider.

**Comment by jeffkl** [comment]
Closing as resolved, feel free to reopen if I haven't answered the question
