### ISSUE TITLE
[BuildTraversal] Publish targets into sub-direcotires of PublishDir

### ISSUE THREAD

**Issue by Stefan75** [microsoft/MSBuildSdks#301]
Hello,

I am currently experimenting with traversal builds.:

I try to migrate an existing azure dev-ops build to traversal project files.
(AFAIK the projects are selected by the build step and msbuild is called once for each project file)
 
Following diagram should describe the directory layout:
```
src
|- ToolA
|  |- TargetA1
|  |  |- Foo.cs
|  |  |- TargetA1.csproj
|  |- TargetA2
|  |  |- Foo.cs
|  |  |- TargetA2.csproj
|  |- TargetA3
|     |- Foo.cs
|     |- TargetA3.csproj
|
|- ToolB
   |- TargetB1
   |  |- Foo.cs
   |  |- TargetB1.csproj
   |- TargetB2
      |- Foo.cs
      |- TargetB2.csproj
```
Some comments:
- There is a `dirs.proj` file in the `src` folder. This traversal project file uses two `ProjectReference` entires to include the `dirs.proj` from ToolA and ToolB
- ToolA and ToolB have their own directory with an own dirs.proj file (where all csproj files are selected)

Objective:
When I use following command line to publish the targets:
```
msbuild .\dirs.proj /t:publish /p:PublishDir=C:\temp\Test /p:Configuration=Debug
```

Then I want the following directory structure:
(each tools in a sperate sub directory)
```
C:\temp\Test
|- ToolA
|  |- TargetA1.dll
|  |- TargetA2.dll
|  |- TargetA3.exe
|
|- ToolB
   |- TargetB1.dll
   |- TargetB2.exe
```

Current state:
- I found no solution to specify a modified `PublishDir` for a `ProjectReference`.
- I found two possible solutions

1. Inside of a traversal project file:
``` xml
<Project Sdk="Microsoft.Build.Traversal">
   ...
  <Target Name="PublishToolA" AfterTargets="Publish">
    <MSBuild Projects="ToolA/dirs.proj" Targets="Publish" Properties="PublishDir=$(PublishDir)\ToolA"/>
  </Target>
</Project>
```

2. Don't use a traversal project file 
``` xml
<Project>
   <Target Name="Build">
      <MSBuild Projects="ToolA/dirs.proj" Targets="Build" />
    </Target>
    <Target Name="Publish">
      <MSBuild Projects="ToolA/dirs.proj" Targets="Publish" Properties="PublishDir=$(PublishDir)\ToolA"/>
    </Target>
</Project>
```

In my understanding, I have to specify all standard targets (e.g. Build, Clean, ...) to *forward* them to the `dirs.proj` of each Tool.
=> A lot of code, source of errors.

Is there a better solution to achieve my goal?

Thank you in advance,
stefan

**Comment by jeffkl** [comment]
At this time, Microsoft.Build.Traversal simply schedules builds in dependency order.  Where outputs go is controlled by the .NET SDK.  I would not recommend that projects share an output folder since it makes the build non-deterministic. 

If you want to get more info on controlling where outputs go, I suggest you open an issue over at https://github.com/dotnet/sdk
