### ISSUE TITLE
Use PackageLicenseExpression in packages built from this repo

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/MSBuildSdks#312]
The SDK packages published from this repo include a [LICENSE.txt](https://github.com/microsoft/MSBuildSdks/blob/50290115103a9164c1e03711e8f2b57c1818e8f5/LICENSE.txt) file, which contains the text of the MIT license:

<https://github.com/microsoft/MSBuildSdks/blob/50290115103a9164c1e03711e8f2b57c1818e8f5/Directory.Build.targets#L27-L28>

However, <https://docs.microsoft.com/en-us/nuget/reference/nuspec#license> recommends that MIT-licensed packages should have `<license type="expression">MIT</license>` instead of referring to a file. In Directory.Build.targets, that would be `<PackageLicenseExpression>MIT</PackageLicenseExpression>`. I believe that would let the NuGet Gallery pages for [Microsoft.Build.NoTargets](https://www.nuget.org/packages/Microsoft.Build.NoTargets/3.2.9/) and other packages display the text "MIT license", like the page for [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/6.0.0) already does.

LICENSE.txt does contain a copyright notice that would not be covered by `<license type="expression">MIT</license>`:

<https://github.com/microsoft/MSBuildSdks/blob/50290115103a9164c1e03711e8f2b57c1818e8f5/LICENSE.txt#L3>

However, almost the same copyright notice is already in the `copyright` element of the generated nuspec, so omitting the copyright notice from the `license` element seems OK. I believe it comes from the Copyright property that Directory.Build.targets sets:

<https://github.com/microsoft/MSBuildSdks/blob/50290115103a9164c1e03711e8f2b57c1818e8f5/Directory.Build.targets#L26>

**Comment by jeffkl** [comment]
This sounds reasonable, I think when the packages were first published, NuGet did not have the feature of using an license expression.  We should update to use this feature.
