### ISSUE TITLE
"Log an error if imported in Directory.Build.props PR" breaks custom project structure

### ISSUE THREAD

**Issue by avivanoff** [microsoft/MSBuildSdks#324]
In our porject we do not use Directory.Build.pros/targets, instead we use custom common props and trargets files. PR #322 breaks our builds. See attached sample project.

[CentralPackageVersions.zip](https://github.com/microsoft/MSBuildSdks/files/7644337/CentralPackageVersions.zip)

**Comment by jeffkl** [comment]
Thanks for filing this, I'll get it fixed soon.

**Comment by avivanoff** [comment]
@jeffkl, thank you for the quick fix. You may also want to update readme.md to clarify Directory.Build.targets usage.
