### ISSUE TITLE
Traversal Sdk project doesn't honor BuildProjectReferences flag

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/MSBuildSdks#335]
When invoking a traversal sdk project with the `--no-dependencies` flag which underneath gets converted to the `BuildProjectReferences=false` property, the projects are still built. This is because the Traversal project currently doesn't check on that flag in its targets file.

I would like to submit a PR for this if that's ok :)

**Comment by jeffkl** [comment]
A Traversal project doesn't really build anything itself, what's the use case to "build" only a traversal project but nothing it points to?

**Comment by ViktorHofer** [comment]
You are right, originally I had some logic in a traversal project as AfterTargets="Build" but IMO traversal projects should only traverse. Closing.
