### ISSUE TITLE
Adding the TargetFramework net6.0-maccatalyst15.2 leads to an error

### ISSUE THREAD

**Issue by edoust** [microsoft/MSBuildSdks#346]
Error Message: 
`The package reference System.Runtime.InteropServices.NFloat.Internal should not specify a version. Please specify the version in 'xxx\Packages.props' or set VersionOverride to override the centrally defined version.`

This worked fine with `net6.0-maccatalyst15.0`

There is no explicit reference to the the mentioned package in my code.

**Comment by edoust** [comment]
As a workaround I am including this in the `CustomBeforeCentralPackageVersionsTargets`

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Update="System.Runtime.InteropServices.NFloat.Internal" IsImplicitlyDefined="true" />
  </ItemGroup>
</Project>
```

**Comment by jeffkl** [comment]
@edoust thanks for posting a workaround.  I'm going to close this since it was fixed in https://github.com/xamarin/xamarin-macios/pull/14532
