### ISSUE TITLE
Using a custom graph protocol is blocked by the Traversal SDK

### ISSUE THREAD

**Issue by aelij** [microsoft/MSBuildSdks#385]
When adding a custom protocol, e.g.
```xml
<ProjectReferenceTargets Include="Foo" Targets="Foo" />
```

Only the root traversal project runs the `Foo` target.

I think the problem is this line:
https://github.com/microsoft/MSBuildSdks/blob/96f2169fe2602f2cfdcb86d21a018e35bed8f1b6/src/Traversal/Sdk/Sdk.targets#L40

Perhaps just remove the protocols the Traversal SDK is handling rather than remove all.

**Comment by jeffkl** [comment]
> Perhaps just remove the protocols the Traversal SDK is handling rather than remove all.

Sounds like a good solution to me, feel free to send a PR
