### ISSUE TITLE
CentralPackageVersions:Enable GlobalPackageReference package not just for analyzers and build-logic

### ISSUE THREAD

**Issue by martinstenhoff** [microsoft/MSBuildSdks#387]
I was hoping to add Nopen.NET (an analyzer that warns about your classes not being either sealed or abstract) to all solution projects using GlobalPackageReference in my Packages.props:
```
<GlobalPackageReference Include="Nopen.NET" Version="1.1.0-beta.23" />
```
The analyzer bit works fine, but this package also contains an attribute [Open] which allows the user to explicitly mark a class as open, which suppresses the warning (and this attribute is not made available via GlobalPackageReference).

I see that GlobalPackageReference packages get a hardcoded `<IncludeAssets>Analyzers;Build;BuildMultitargeting;BuildTransitive</IncludeAssets>`

Would it be possible to add support for allowing IncludeAssets to be overridden in the GlobalPackageReference tag?

```
<GlobalPackageReference Include="Nopen.NET" Version="1.1.0-beta.23" >
   <IncludeAssets>[The desired list of assets]</IncludeAssets>
</GlobalPackageReference>
```
Which I think would enable using a cross cutting package like this across the entire solution.

**Comment by jeffkl** [comment]
Setting the metadata on the `GlobalPackageReference` item should work:

```xml
<GlobalPackageReference Include="Nopen.NET" Version="1.1.0-beta.23" IncludeAssets="All" />
```

Microsoft.Build.CentralPackageVersions declares an ItemDefinitionGroup which just sets default metadata unless you specify something different:

https://github.com/microsoft/MSBuildSdks/blob/1ffaca3688b4cda576a1dcfd094e386d1be75ebf/src/CentralPackageVersions/Sdk/Sdk.targets#L45-L63

It then copies `GlobalPackageReference` items to `PackageReference` with all their metadata:

https://github.com/microsoft/MSBuildSdks/blob/1ffaca3688b4cda576a1dcfd094e386d1be75ebf/src/CentralPackageVersions/Sdk/Sdk.targets#L105-L109

Does it not seem to be working?

**Comment by martinstenhoff** [comment]
I tried with:
`<GlobalPackageReference Include="Nopen.NET" Version="1.1.0-beta.23" IncludeAssets="All" />`
and that works.

I now also tried with: 
```
<GlobalPackageReference Include="Nopen.NET" Version="1.1.0-beta.23" >
   <IncludeAssets>All</IncludeAssets>
</GlobalPackageReference>
```
and that also works so I obviously made a mistake with my IncludeAssets. Most likely I used the following incorrect _IncludeAssets_ that was missing _compile_:
```
<GlobalPackageReference Include="Nopen.NET" Version="1.1.0-beta.23" >
   <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</GlobalPackageReference>
```
