### ISSUE TITLE
launch: program '' does not exist.

### ISSUE THREAD

**Issue by Satvik-web** [microsoft/MSBuildSdks#388]
![Screenshot 2022-09-28 at 11 53 58 AM](https://user-images.githubusercontent.com/72124172/192703493-84489aa2-65cf-4e81-91ac-3f1c5b054d7c.png)

Steps to Reproduce:
1. Create an asp.net core app
2. Start the program with debugging.

Is there any way to fix the debugger.
The project runs properly without debugging.

**Comment by Satvik-web** [comment]
![Screenshot 2022-09-28 at 11 57 00 AM](https://user-images.githubusercontent.com/72124172/192703976-a222f61e-8867-489f-95b3-84633964b639.png)

**Comment by Satvik-web** [comment]
Using VS for Mac 2019 build 17 - 8.10.14

**Comment by jeffkl** [comment]
@Satvik-web I don't think this repository contains any logic which would cause this error.  I would suggest filing a feedback ticket in VS for Mac with the problem details so someone can investigate.
