### ISSUE TITLE
DirExclude seems to only accept space-separated folder names

### ISSUE THREAD

**Issue by Matteo-T** [microsoft/MSBuildSdks#402]
I'm using Microsoft.Build.Artifacts 4.1.0 and I noticed that, contrary to what stated in the documentation, the only valid separator seems to be the space.

My project looked like this:

```xml
 <!-- ... -->
    </PropertyGroup>
        <CulturesThatWeDoNotShip>ar;bg;ca;da;el;et;eu;fi;gl;he;hi;hr;hu;id;kk;lt;lv;ms;nl;no;pt-pt;ro;sk;sl;sr-Cyrl;sr-Latn;sv;th;uk;vi</CulturesThatWeDoNotShip>
    </PropertyGroup>

 <!-- ... -->

    <ItemGroup>
        <Artifact Include="$(PkgMyFatPackage)\resources" 
            FileMatch="*.*" 
            IsRecursive="true"
            DirExclude="$(CulturesThatWeDoNotShip)"
            DestinationFolder="$(ArtifactsPath)\Somewhere" />
    </ItemGroup>
 <!-- ... -->
```

Not a big deal as I can use that instead, but a little confusing.

Could you either fix the documentation or the code?

Thanks!

**Comment by jeffkl** [comment]
Thanks for filing this, I'll get a fix out soon

**Comment by Matteo-T** [comment]
Thanks @jeffkl for fixing it so quickly. 

Btw, is there a way to express that I want to exclude a folder that contains spaces? 
It feels like
```xml
DirExclude="This And That"
```
would be interpreted as "Exclude 3 directories" instead of "Exclude 1 directory" (my current 'workaround' is to use

```xml
DirExclude="This?And?That"
```
and hope I don't have anything like "ThisXAndYThat" that I want to include :-)

Is this a case of "user education" or "please long a new issue and we'll see what we can do about it"? :)

**Comment by jeffkl** [comment]
> Btw, is there a way to express that I want to exclude a folder that contains spaces?

Not at the moment no, this is the basic split logic:

https://github.com/microsoft/MSBuildSdks/blob/252b32490bba60105bed8828a8ea7c18d69e5701/src/Artifacts/Tasks/RobocopyMetadata.cs#L321

If anyone wants that, we'll need a new issue.  Using `?` as a wildcard would _probably_ work but I haven't tested it 😄
