### ISSUE TITLE
[NoTargets] FileWrites has no impact on build incrementalism

### ISSUE THREAD

**Issue by stan-sz** [microsoft/MSBuildSdks#422]
Taking the repo's [example](https://github.com/microsoft/MSBuildSdks/blob/main/src/NoTargets/README.md#example) for repro, the items written in `FileWrites` are created too late for `_CleanGetCurrentAndPriorFileWrites` to be processed. Is this an issue with the example (fine-tune Before/AfterTargets) or with the NoTargets SDK?

Here's the graphical representation of the order of actions:

![image](https://user-images.githubusercontent.com/37585349/220083983-a0399b1a-f890-4e9e-a0bf-10b78c348678.png)

**Comment by jeffkl** [comment]
Yeah I guess `_CleanGetCurrentAndPriorFileWrites` runs as part of `IncrementalClean` which runs as part of `CoreBuild` and the example runs before `AfterBuild`.  We can update the example to run as part of `PrepareForRun` instead which is what triggers copying files to the output directory.

```xml
<Target Name="CopyFiles" BeforeTargets="PrepareForRun">
```

Do you want to update the example?
