### ISSUE TITLE
Support dynamically skipping projects

### ISSUE THREAD

**Issue by jeffkl** [microsoft/MSBuildSdks#438]
At the moment, users have to manually implement the ability to condition out project references in Traversal projects:

```xml
<Project Sdk="Microsoft.Build.Traversal">
  <ItemGroup>
    <ProjectReference Include="src\Common\Common.csproj" />
    <ProjectReference Include="src\App\App.csproj" />
    <ProjectReference Include="src\WebApplication\WebApplication.csproj" Condition="'$(DoNotBuildWebApp)' == 'true'" />
  </ItemGroup>
</Project>
```

It would be very handy for Microsoft.Build.Traversal to have a built-in mechanism for skipping projects.  It would also be great if Microsoft.Build.Traversal could extend Visual Studio solution file builds to dynamically skip projects.  This would allow a repo owner to skip projects when a user uses `dotnet build` instead of `MSBuild.exe` since not all project types are buildable with `dotnet build`.

**Comment by vikukush** [comment]
This new feature breaks the build because GetProjectsToSkip runs before Restore and does _not_ ignore missing imports from packages, causing errors like
error MSB4019: The imported project "C:\msbuild\CompileModule.proj" was not found. Confirm that the expression in the Import declaration "\msbuild\CompileModule.proj" is correct, and that the file exists on disk.

**Comment by vikukush** [comment]
@jeffkl could you please create a unit test about this? This seems to be a rather standard scenario that got broken; if it's not automatically tested, then it's an omission.

**Comment by jeffkl** [comment]
@vikukush you can skip updating to the latest version if its broken for you or you can disable the feature by setting the MSBuild property `SkipProjects` to `false` for now.  I'll work on a fix in about two weeks when I'm back from vacation.
