### ISSUE TITLE
Project file using NoTargets refuses to load in Visual Studio

### ISSUE THREAD

**Issue by wjk** [Microsoft/MSBuildSdks#44]
Title really says it all. An error dialog says "Project file is incomplete. Project file is missing required imports" but fails to say what those imports are. I am using version 1.0.39 of NoTargets and Visual Studio 15.7.5. Could someone help me out here? Thanks!

**Comment by jeffkl** [comment]
Just to be sure I’m investigating the right issue, can you please post your project?

**Comment by wjk** [comment]
Here's a repro: [SdkRepro.zip](https://github.com/Microsoft/MSBuildSdks/files/2186656/SdkRepro.zip)

Open the solution, and try to add the `SdkRepro\SdkRepro.msbuild` project.

**Comment by jeffkl** [comment]
Yeah it repros for me.  @davkean do you happen to know if anything changed in 15.7.X  that would cause this?  The SDK is importing `Microsoft.NET.Sdk` and worked before.  I'm installing some older versions of VS to figure out when it broke.

**Comment by davkean** [comment]
This error means that we can't find basic set of rules for the project system. Usually means that "Microsoft.Managed.DesignTime.targets" is not in the import graph.

"MSBuild /pp" is your friend here.

**Comment by jeffkl** [comment]
@davkean thank you knowing which file isn't being imported helped me tremendously!

@wjk It looks like a simple fix, however I'm going out of town tomorrow so expect a delay.  Sorry about that!

**Comment by jeffkl** [comment]
The fix for this is available in the latest package: https://www.nuget.org/packages/Microsoft.Build.NoTargets/1.0.40

**Comment by DoCode** [comment]
I think this is not solved!  
A project with the latest Bits (VS16) cannot open a project with `Microsoft.Build.NoTargets` SDK.

We should re-open this issue!

**Comment by jeffkl** [comment]
@DoCode I added a sample to our repo to see if I had any issues:

https://github.com/Microsoft/MSBuildSdks/tree/master/samples/NoTargets/SampleNoTargets

It loads in Visual Studio 15.7 and the latest 15.9.4.  Can you take a look at the sample and see if maybe you're doing something wrong?  If it won't load, I'll need more details to investigate.
