### ISSUE TITLE
Traversal: Do not seem that static graph are supported

### ISSUE THREAD

**Issue by hknielsen** [microsoft/MSBuildSdks#445]
When using the `isolate` constraint with Traversal SDK, alot of errors are hinting that [static graph](https://github.com/dotnet/msbuild/blob/main/documentation/specs/static-graph.md#static-graph) is not supported.
```
C:\Users\haral\.nuget\packages\microsoft.build.traversal\4.0.0\Sdk\Traversal.targets(267,5): error :     is building project "C:\UnitySrc\Unity\temp\TestSt
uffOut\ConsoleApp2\ClassLibrary1\ClassLibrary1.csproj" with global properties [C:\UnitySrc\Unity\temp\TestStuffOut\ConsoleApp2\Root\Root.csproj]
C:\Users\haral\.nuget\packages\microsoft.build.traversal\4.0.0\Sdk\Traversal.targets(267,5): error :     (MSBuildRestoreSessionId=0183a69c-084e-49e1-97ce-e
ac8eace6482) [C:\UnitySrc\Unity\temp\TestStuffOut\ConsoleApp2\Root\Root.csproj]
C:\Users\haral\.nuget\packages\microsoft.build.traversal\4.0.0\Sdk\Traversal.targets(267,5): error :     with the (ShouldSkipProject) target(s) but the bui
ld result for the built project is not in the engine cache. In isolated builds this could mean one of the following: [C:\UnitySrc\Unity\temp\TestStuffOut\C
onsoleApp2\Root\Root.csproj]
```

Global properties are passed to the MSBuild tasks, and thats what are giving issues.
Are the Traversal SDK not meant for usage with Static Graph / Isolate? Or maybe im missing to pass some properties, as also are needed to be passed to when using Restore + Nuget with static graph :)?

**Comment by hknielsen** [comment]
Hi @jeffkl, sorry for the direct ping 😅  Is this something that could be supported? We would like to enforce static-graph for all the big performance gains and caching possibilities. So looking at options

**Comment by jeffkl** [comment]
The `MSBuildRestoreSessionId` property is only set during restore, so you'll probably need to restore first and build second:

```
msbuild /t:restore
msbuild /restore:false /graph /isolate
```

The `ShouldSkipProject` was enabled by default in version 4.0.0 but is now off by default in 4.1.0 so it should work again with `/isolate`.

**Comment by hknielsen** [comment]
@jeffkl oh, tried the new version and now it works! As long as `TraversalSkipUnsupportedProjects` is false AFAICT.
`msbuild /t:restore /graph /isolate /p:RestoreUseStaticGraphEvaluation=true` Works.

I think we should add a test to make sure that restore & build works with `isolation` mode enabled. What do you think?

**Comment by jeffkl** [comment]
Yeah that sounds reasonable, feel free to contribute it.
