### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Dataflow,

### ISSUE THREAD

**Issue by PiDiBi** [microsoft/MSBuildSdks#455]
used 
`"Microsoft.Build.CopyOnWrite" : "1.0.262"`

The "Copy" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks.Dataflow, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Build.Tasks.Copy.CopyParallel(CopyFileWithState copyFile, Int32 parallelism, List`1& destinationFilesSuccessfullyCopied)
   at Microsoft.Build.Tasks.Copy.Execute(CopyFileWithState copyFile, Int32 parallelism)
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

no other log messages found

![image](https://github.com/microsoft/MSBuildSdks/assets/12524436/07448b4d-6b52-4100-8096-21ecd504c488)

but in other part of builds I can see SDK works

![image](https://github.com/microsoft/MSBuildSdks/assets/12524436/49b30e8a-0abd-4f10-b013-d911b3cb4b9e)

It's happening in 1ES managed pool so can't easily enable and see Fusion log

**Comment by PiDiBi** [comment]
and just to be clear the file missing is not file being copied

![image](https://github.com/microsoft/MSBuildSdks/assets/12524436/7696240b-1c17-4162-9551-d8c8a5f12512)

**Comment by PiDiBi** [comment]
I was able to simulate it in devbox VM with ReFS enabled, enabled fuselog got this

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: The "Copy" task failed unexpectedly. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Dataflow, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: File name: 'System.Threading.Tasks.Dataflow, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018:    at Microsoft.Build.Tasks.Copy.CopyParallel(CopyFileWithState copyFile, Int32 parallelism, List`1& destinationFilesSuccessfullyCopied) [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018:    at Microsoft.Build.Tasks.Copy.Execute(CopyFileWithState copyFile, Int32 parallelism) [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018:  [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: Running under executable  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: --- A detailed error log follows.  [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018:  [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: === Pre-bind state information === [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: DisplayName = System.Threading.Tasks.Dataflow, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018:  (Fully-specified) [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Appbase = file:///C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/ [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Initial PrivatePath = NULL [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: Calling assembly : Microsoft.Build.CopyOnWrite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: === [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: This bind starts in LoadFrom load context. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load(). [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Using application configuration file: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe.Config [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Using host configuration file:  [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Post-policy reference: System.Threading.Tasks.Dataflow, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/System.Threading.Tasks.Dataflow.DLL. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: WRN: Comparing the assembly name resulted in the mismatch: Major Version [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/System.Threading.Tasks.Dataflow/System.Threading.Tasks.Dataflow.DLL. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/System.Threading.Tasks.Dataflow.EXE. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/System.Threading.Tasks.Dataflow/System.Threading.Tasks.Dataflow.EXE. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Attempting download of new URL file:///D:/.tools/.nuget/packages/microsoft.build.copyonwrite/1.0.262/build/netstandard2.0/System.Threading.Tasks.Dataflow.DLL. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Attempting download of new URL file:///D:/.tools/.nuget/packages/microsoft.build.copyonwrite/1.0.262/build/netstandard2.0/System.Threading.Tasks.Dataflow/System.Threading.Tasks.Dataflow.DLL. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Attempting download of new URL file:///D:/.tools/.nuget/packages/microsoft.build.copyonwrite/1.0.262/build/netstandard2.0/System.Threading.Tasks.Dataflow.EXE. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018: LOG: Attempting download of new URL file:///D:/.tools/.nuget/packages/microsoft.build.copyonwrite/1.0.262/build/netstandard2.0/System.Threading.Tasks.Dataflow/System.Threading.Tasks.Dataflow.EXE. [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4018:  [D:\src\antares-websites\dev\src\Hosting\crashmon\crashmon\crashmon.csproj]

**Comment by PiDiBi** [comment]
D:\src\antares-websites\dev>dotnet --list-sdks
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.408 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]

D:\src\antares-websites\dev>dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by PiDiBi** [comment]
nicer formatting 

![image](https://github.com/microsoft/MSBuildSdks/assets/12524436/59fa14f9-e024-41f4-a8f8-beaf4925d06b)

**Comment by PiDiBi** [comment]
The TPL Dataflow Library (the [System.Threading.Tasks.Dataflow](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow) namespace) is not distributed with .NET. To install the [System.Threading.Tasks.Dataflow](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow) namespace in Visual Studio, open your project, choose Manage NuGet Packages from the Project menu, and search online for the System.Threading.Tasks.Dataflow package. Alternatively, to install it using [the .NET Core CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/), run dotnet add package System.Threading.Tasks.Dataflow.

**Comment by PiDiBi** [comment]
image the VM is based on
/MicrosoftVisualStudio/visualstudio2022/vs-2022-ent-latest-win11-n-gen2/latest

talked with Andy and msbuild is redistributing that dll and on the VM where it fails isversion 6

![image](https://github.com/microsoft/MSBuildSdks/assets/12524436/973a583f-7d72-45a2-bdaf-50c836233c18)

**Comment by PiDiBi** [comment]
this is the problem and workaround for local VM
to update VS
but can't be used for VM in build pools
![image](https://github.com/microsoft/MSBuildSdks/assets/12524436/54ffe17b-b1ed-43a9-ac58-321fb4c465c7)

**Comment by AndyGerlicher** [comment]
Fixed with #457
