### ISSUE TITLE
Microsoft.Build.Tasks.Copy winerror 1005 with unformatted/raw drive

### ISSUE THREAD

**Issue by CZEMacLeod** [microsoft/MSBuildSdks#459]
```
error MSB4061: The "Copy" task could not be instantiated from "C:\Users\xxx\.nuget\packages\microsoft.build.copyonwrite\1.0.263\build\netstandard2.0\Microsoft.Build.CopyOnWrite.dll". 
1>    C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB4061: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Copy' threw an exception. ---> System.ComponentModel.Win32Exception: Failed retrieving volume information for S:\ with winerror 1005
```

My S:\ drive is going to be a ReFS drive and hold my source, but I am currently using Win11 Canary and don't have DevDrv yet, so the partition is there, but unformatted.
(I had got as far as `format S: /devdrv` but was told `The requested feature is not yet available, stay tuned.` ;) )
However, when including the CoW package, I now crash out with `winerror 1005`.
Diskmanager shows the partition as RAW.

Removing the Drive Letter allowed me to continue building the source (which was on my C: drive)

**Comment by AndyGerlicher** [comment]
Can you create a DevDrive from the UI? I think it's something like Settings App -> System -> Storage -> Disks & Volumes. Not sure if what I'm looking at is current though. I had thought DevDrive was released for testing so I'm surprised by that.

Also, for the error message, do you know why it's trying to check the S: drive? That seems like a somewhat reasonable result if you are trying to copy files from a valid drive to an unformatted drive. But if your build has no reference to S: (and no overridden env variables pointing to S:\) and it fails because S:\ happens to exist, that would need to get fixed. Can you check your binlog to see if anything in the build points to that drive?

**Comment by CZEMacLeod** [comment]
@AndyGerlicher DevDrive is not available on Canary unfortunately. I missed the window to switch tiers a while back and haven't had the time or energy to rebuild my entire workstation. I do have Dev Home which is interesting and I hope gets some more love.

As it is, it looks like this was a false correlation on my part with regard to removing the drive letter. 
The latest version, 1.0.263, appears to work even with the RAW partition having a drive letter.

The issue was actually that I had copied and pasted the line from the readme
```xml
<GlobalPackageReference Include="Microsoft.Build.CopyOnWrite" Version="1.0.0" />
```
, although I had changed `GlobalPackageReference` to `PackageReference` to install it normally, but via my `Directory.Build.props` file.
(It should be noted that the readme doesn't really suggest that you can install it as a normal package at all!)
There isn't a `1.0.0` published so it had resolved `1.0.240` unbeknownst to me. I then changed the version to `1.0.263` that I could see from the nuget package badge [![NuGet](https://img.shields.io/nuget/v/Microsoft.Build.CopyOnWrite.svg)](https://www.nuget.org/packages/Microsoft.Build.CopyOnWrite)
 [![NuGet](https://img.shields.io/nuget/dt/Microsoft.Build.CopyOnWrite.svg)](https://www.nuget.org/packages/Microsoft.Build.CopyOnWrite)

However, it had already loaded the DLL with the older task into memory and that has a problem.
When I removed the drive letter, I had closed and re-opened VS2022 at the same time, to ensure that any static caches in the code cleared (which I had seen from having a quick look at the code). This meant the newer DLL loaded and didn't have the issue anyway.

I think the resolution to this is to change the readme to not have explicit version numbers e.g. use something like 1.0.x to make it clear not to actually copy that in, and perhaps to make it clearer that you can actually use it without CPM/CPV or as an SDK import.
It might also be an idea to un-list the older versions that have bugs/issues? I can see people using this with e.g. SD Cards with linux partitions on them, (like for a PI), which would probably also fail on the older version.

I'm also not sure that checking the root drive is the best mechanism anyway. I would have preferred to mount my ReFS under an existing path and moved my code over to it, so all my existing paths still matched. I'd probably still have to adjust my nuget packages path, but I'm going to have to do that anyway, when I eventually get this to work locally.
I have been using it on my build server successfully though.

**Comment by CZEMacLeod** [comment]
For reference the full errors were:
```
warning NU1603: xxx depends on Microsoft.Build.CopyOnWrite (>= 1.0.0) but Microsoft.Build.CopyOnWrite 1.0.0 was not found. An approximate best match of Microsoft.Build.CopyOnWrite 1.0.240 was resolved.
```
and
```
error MSB4061: The "Copy" task could not be instantiated from "C:\Users\xxx\.nuget\packages\microsoft.build.copyonwrite\1.0.240\build\..\lib\netstandard2.0\Microsoft.Build.CopyOnWrite.dll". 
error MSB4061: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Copy' threw an exception. ---> System.ComponentModel.Win32Exception: Failed retrieving volume information for S:\ with winerror 1005
error MSB4061:    at Microsoft.CopyOnWrite.Windows.NativeMethods.ThrowSpecificIoException(Int32 lastErr, String message) in C:\CoW\lib\Windows\NativeMethods.cs:line 30
error MSB4061:    at Microsoft.CopyOnWrite.Windows.VolumeInfoCache.GetVolumeInfo(VolumePaths volumePaths) in C:\CoW\lib\Windows\VolumeInfoCache.cs:line 148
error MSB4061:    at Microsoft.CopyOnWrite.Windows.VolumeInfoCache.BuildFromCurrentFilesystem() in C:\CoW\lib\Windows\VolumeInfoCache.cs:line 36
error MSB4061:    at Microsoft.CopyOnWrite.CopyOnWriteFilesystemFactory.Create() in C:\CoW\lib\CopyOnWriteFilesystemFactory.cs:line 48
error MSB4061:    at System.Lazy`1.CreateValue()
error MSB4061:    at System.Lazy`1.LazyInitValue()
error MSB4061:    at Microsoft.Build.Tasks.Copy..cctor()
error MSB4061:    --- End of inner exception stack trace ---
error MSB4061:    at Microsoft.Build.Tasks.Copy..ctor()
error MSB4060: The "Copy" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
```
This clearly shows the error to be in package version 1.0.240, however if you change the version and don't unload and reload, then the older Task is still loaded in memory and will be called from the newer .target file. I think the original error message is actually wrong here, as that is not the location of the DLL in use/in memory, but the updated location it should be using.

It does point to the fact that the `VolumeInfoCache` should probably have some sort of error handling in it for `BuildFromCurrentFilesystem` or perhaps `VolumeEnumerator` should check for a valid filesystem... although both of these are in https://github.com/microsoft/CopyOnWrite/ rather than here...

**Comment by erikmav** [comment]
winerror 1005 is `ERROR_UNRECOGNIZED_VOLUME` which was added to the CoW package as an ignored error condition in Feb 2023 (CoW package version 0.3.2) and included in the Copy task in Microsoft.Build.CopyOnWrite versions 1.0.242 and later.
