### ISSUE TITLE
Microsoft.Build.Artifacts package should not depend on System.Threading.Tasks.Dataflow

### ISSUE THREAD

**Issue by bording** [microsoft/MSBuildSdks#490]
The Microsoft.Build.Artifacts package currently has a dependency on System.Threading.Tasks.Dataflow:

![image](https://github.com/microsoft/MSBuildSdks/assets/753669/4cf1b317-f511-49ce-9639-d087cedaa53e)

This package dependency means that a copy of `System.Threading.Tasks.Dataflow.dll` is copied into the output of projects using Microsoft.Build.Artifacts.

From what I can tell, this dependency is a mistake. While `Microsoft.Build.Artifacts.dll` does have a reference to `System.Threading.Tasks.Dataflow.dll`, the assembly is already shipped inside the package:

![image](https://github.com/microsoft/MSBuildSdks/assets/753669/984265d3-ffeb-461f-9d48-c5683b95208a)

There should be no reason to have the package dependency. It would be great to get it removed!

**Comment by jeffkl** [comment]
Yeah this should be easy to fix, we need `PrivateAssets=All` [here](https://github.com/microsoft/MSBuildSdks/blob/main/src/Artifacts/Microsoft.Build.Artifacts.csproj#L17).
