### ISSUE TITLE
How to specify build order with Microsoft.Build.Traversal?

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/MSBuildSdks#50]
If I have some .proj file that cannot be referenced by a .csproj file, how can I specify the build order explicitly?

For example:
A.proj generate some cs file that will be used by B.csproj, how can I make A.proj be built before B.csproj? Will MSBuild detect and help me sort them?

**Comment by jeffkl** [comment]
You can specify build order with a Visual Studio Solution File (.SLN) or using ProjectReferences.  I wouldn't recommend using a solution file because the build order is only respected when building the solution file.

You should be able to add a project reference to your `.proj` project just fine.  You may need to set some metadata:

```xml
<ItemGroup>
  <ProjectReference Include="..\ProjectB\ProjectB.proj">
    <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
  </ProjectReference>
</ItemGroup>
```

Are you getting a specific error when adding a project reference to your `.proj`?

**Comment by yhvicey** [comment]
@jeffkl I created two project files to test the behavior:

```xml
<!-- .csproj, ignored other sections -->
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="/path/to/proj.proj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
</Project>
```

```xml
<!-- .proj, ignored other sections -->
<Project>
  <Target Name="Build">
    <Message Text="Proj built" Importance="High" />
  </Target>
</Project>
```

However when I build csproj I didn't see the message from proj. Is this the right way to use that?

**Comment by jeffkl** [comment]
It looks like and SDK-style CSPROJ ProjectReference must have a target named `GetTargetFramework` according to the logs.

This worked for me:
## 50-project.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="50-reference.proj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
</Project>
```

## 50-reference.proj
```xml
<Project>
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
  
  <Target Name="Build" AfterTargets="Build">
    <Message Text="Proj built" Importance="High" />
  </Target>
  
  <Target Name="GetTargetFrameworks" Returns="@(_ThisProjectBuildMetadata)">
    <ItemGroup>
      <_ThisProjectBuildMetadata Include="$(MSBuildProjectFullPath)" TargetFrameworks="$(TargetFramework)" HasSingleTargetFramework="true" IsRidAgnostic="true" />
    </ItemGroup>
  </Target>
</Project>
```

## Output
```
D:\Stuff>msbuild 50-project.csproj /bl /clp:v=m;summary
Microsoft (R) Build Engine version 15.9.10-preview+g0f6f8379ea for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\Visual Studio 2017 Preview\MSBuild\15.0\bin\msbuild.exe /bl /clp:v=m;summary 50-project.csproj
  Proj built
  50-project -> D:\Stuff\bin\Debug\net46\50-project.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.60
```

**Comment by yhvicey** [comment]
WOW, that's a little bit complex. Is there any doc about how CoreXT did this? Could this be implemented by this SDK?

**Comment by jeffkl** [comment]
Of course, you can use [`Microsoft.Build.NoTargets`](https://github.com/Microsoft/MSBuildSdks/tree/master/src/NoTargets):


```xml
<Project Sdk="Microsoft.Build.NoTargets/1.0.40">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
  
  <Target Name="MyTarget" AfterTargets="Build">
    <Message Text="Proj built" Importance="High" />
  </Target>
</Project>
```

**Comment by yhvicey** [comment]
It seems Microsoft.Build.NoTargets won't work without TargetFramework. Is it by design?

**Comment by yhvicey** [comment]
Got it. Thanks for your help!
