### ISSUE TITLE
What is the recommended way to consume Microsoft.Build.CopyOnWrite in a cross-platform repo?

### ISSUE THREAD

**Issue by alexrp** [microsoft/MSBuildSdks#526]
I understand that [Microsoft.CopyOnWrite](https://github.com/microsoft/CopyOnWrite) does not currently work on non-Windows, and I would assume the same applies to Microsoft.Build.CopyOnWrite. So what is the recommended pattern for consuming this package in a repo that's expected to be built on both Windows and Unix platforms? (The idea would be to take advantage of CoW on Windows and gracefully fall back to normal copy on Unix.)

**Comment by erikmav** [comment]
I use it in a 2-OS repo daily. On Linux and Mac the CoW base library returns `false` from the method that asks whether CoW works between paths or in a directory tree. Which means on Linux and Mac that regular `File.Copy` is used instead of a CoW link.

I've not started any work to add in the Linux and Mac clone calls in the base library. If you're interested in contributing I'd welcome the added functionality.

**Comment by erikmav** [comment]
I posted a PR with a doc clarification. Also of note, .NET 8 added macOS CoW (clone) usage in File.Copy with https://github.com/dotnet/runtime/pull/79243

**Comment by erikmav** [comment]
Also added the net8 info to the base libary in https://github.com/microsoft/CopyOnWrite/pull/37

**Comment by erikmav** [comment]
Thanks for finding the Linux PR, I had not seen that before. Pushed an iteration of the PR for this repo with this clarification that answers your Windows question:

On Linux and Mac the current behavior is to always fall back to regular file copies (`File.Copy`), however `File.Copy` automatically uses CoW for [Linux](https://github.com/dotnet/runtime/pull/64264) (starting in .NET 7) and [Mac](https://github.com/dotnet/runtime/pull/79243) (.NET 8). A similar PR for Windows did not make it into .NET, however there is [work underway](https://devblogs.microsoft.com/engineering-at-microsoft/copy-on-write-in-win32-api-early-access/) to integrate CoW into the Windows API in a possible future release.

**Comment by erikmav** [comment]
Added Linux info to CoW library in https://github.com/microsoft/CopyOnWrite/pull/38

**Comment by alexrp** [comment]
Will go ahead and close this one then. Thanks for the clarifications!
