### ISSUE TITLE
How can I tell Microsoft.Build.CopyOnWrite is working? [Question]

### ISSUE THREAD

**Issue by titobf** [microsoft/MSBuildSdks#545]
I have created the file "Directory.Packages.Props" suggested here [Usage in Directory.Packages.Props](https://github.com/microsoft/MSBuildSdks/tree/main/src/CopyOnWrite#usage-in-directorypackagesprops). 

Now, how can I tell this build task and copy-on-write has been actually enabled? Is there a message somewhere? Maybe in the build logs inside Visual Studio? 

Thanks in advance.

**Comment by erikmav** [comment]
When a CoW link is created there is currently a low priority MSBuild log message emitted. See the source code at https://github.com/microsoft/MSBuildSdks/blob/091be5b2ecff7353795e6510dd8f893e35da13a3/src/CopyOnWrite/Copy.cs#L999

**Comment by titobf** [comment]
Thanks. I was not seeing that message by just using "Directory.Packages.props" on the solution folder. 
Now I went to Visual Studio -> Manage Nuget Packages for Solution -> installed Microsoft.Build.CopyOnWrite on every project. 
Now the message appears several times.
