### ISSUE TITLE
Anyway to implement "Test on Build" with Traversal?

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/MSBuildSdks#58]
It seems most dotnet core test projects have a `VSTest` target and it will start the testing. However, normal projects using "Microsoft.Net.Sdk" have this target as well, is there a way to distinguish them and then invoke `VSTest` target on right projects?

**Comment by yhvicey** [comment]
Or maybe this option should be added to dotnet/sdk.

**Comment by jeffkl** [comment]
I don't think projects have the `VSTest` target unless they have a package reference to `Microsoft.NET.Test.Sdk`.

https://github.com/Microsoft/vstest/blob/3decca033435d70f6380c77214aeac38fb54911b/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.targets#L28

Traversal can call the `VSTest` target on every project and it can skip the project if the target doesn't exist.  Is this not the behavior you are seeing?

**Comment by yhvicey** [comment]
calling `dotnet test` on newly created classlib project targeting sdk `2.1.403` hits below error:
```
$ dotnet new classlib
// create a global.json and target sdk version to 2.1.403
$ dotnet test
Build started, please wait...
Build completed.

Test run for <ProjectDll>(.NETStandard,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
System.IO.FileNotFoundException: Unable to find tests for <ProjectDll>. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate. Rerun with /diag option to diagnose further.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
```
And seems this error gone in 2.1.500. Never mind, I'll upgrade my sdk version, thanks
