### ISSUE TITLE
CentralPackageVersions not work with APS.NET Core 2.2

### ISSUE THREAD

**Issue by kevineger** [Microsoft/MSBuildSdks#65]
## Repro Steps

- Create a new sln: `dotnet new sln -n MySln`
- Create a new project `dotnet new console -n MyConsoleApp`
- Add that project to the sln: `dotnet sln ./MySln.sln add ./MyConsoleApp`
- Add the `CentralPackageVersions` SDK to the `.csproj`
- Add a reference to `Microsoft.AspNetCore`
- Create the `Packages.props` file alongside the `.sln`
- Build the project

### Actual behavior

`The package reference 'Microsoft.AspNetCore' must have a version defined in 'C:\Users\keeger\Downloads\PackageTest\Packages.props'.`

Adding `<PackageReference Update="Microsoft.AspNetCore" />` (without the `Version`) to the `Packages.props` does not resolve the problem. Only adding an explicit version as a `VersionOverride` fixes it.

**This is problematic** as [the .Net docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.2) specify _When the version is not specified, an implicit version is specified by the SDK, that is, Microsoft.NET.Sdk.Web. We recommend relying on the implicit version specified by the SDK and not explicitly setting the version number on the package reference._

### Expected behavior

`Microsoft.AspNetCore` can be added to `Packages.props` without an explicit version.

**Comment by jeffkl** [comment]
I am a little unfamiliar with the web SDK so I dug into this a little.  The version is only set for you if:

1. You reference `Microsoft.AspNetCore.All` or `Microsoft.AspNetCore.App`
2. Your project references the SDK `Microsoft.NET.Sdk.Web`

Your console app will reference the SDK `Microsoft.NET.Sdk` and your package reference you mentioned above is `Microsoft.AspNetCore`.  

When an SDK sets a version for you, it also sets the metadata item `IsImplicitlyReferenced` so that `CentralPackageVersions` will ignore it.  I can't find the source for the `Microsoft.NET.Sdk.Web` but here's a snippet from my disk:

```xml
<PackageReference Update="$(_AspNetCoreAllPackageName)" Condition="'@(_AspNetCoreAllReference-&gt;Count())' == '1' AND '@(_ExplicitAspNetCoreAllReference-&gt;Count())' == '0'">
  <Version>$(AspNetCoreAllRuntimeFrameworkVersion)</Version>
  <IsImplicitlyDefined>true</IsImplicitlyDefined>
  <PrivateAssets>All</PrivateAssets>
  <Publish>true</Publish>
</PackageReference>
```

You will need to use a different dotnet template:

```
dotnet new web -n MyWebApp
```

If you want to use the `Microsoft.AspNetCore` package in a console application, you will need to specify the version in `Packages.props` because the SDK won't set the version for you.

**Comment by kevineger** [comment]
Thanks for the prompt reply @jeffkl !

Your breakdown makes total sense. I still think it makes total sense to have `Microsoft.AspNetCore.App` determined from the runtime implicitly, so I think the best approach is to copy paste the implicit reference you highlight above into `Packages.props`.

For completeness, this is my `Packages.props` with that:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Centrally Managed Package Versions -->
  <ItemGroup>
    <!-- It is recommended to not specify a version for the metapackage https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app -->
    <PackageReference Update="Microsoft.AspNetCore.App">
      <Version>$(AspNetCoreAllRuntimeFrameworkVersion)</Version>
      <IsImplicitlyDefined>true</IsImplicitlyDefined>
      <PrivateAssets>All</PrivateAssets>
      <Publish>true</Publish>
    </PackageReference>
    <!-- Example of an explicitly versioned package -->
    <PackageReference Update="xunit" Version="[2.4.0]" />
  </ItemGroup>
</Project>
```

**Comment by kevineger** [comment]
Closing issue with [solution as referenced above](https://github.com/Microsoft/MSBuildSdks/issues/65#issuecomment-463727811).

**Comment by japj** [comment]
I am also running into this (VS2017, dotnet sdk 2.2.105), but the solution did not seem to work.

I found that EnableWebSdkImplicitPackageVersions is default set to false which causes `Microsoft.NET.Sdk.Web\Sdk\Sdk.DefaultItems.targets` not to be imported.

Would it be useful to hook the ApplyImplicitVersions target as a dependency?
