### ISSUE TITLE
CentralPackageVersions does not support F# 

### ISSUE THREAD

**Issue by jmecosta** [microsoft/MSBuildSdks#90]
Hi,

if i create a F# project and include <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.29" />

i get this error 
```
The package reference 'FSharp.Core' should not specify a version.  Please specify the version in 'D:\prod\structures\Packages.props' or set VersionOverride to override the centrally defined version.	
```
Supose the FSharp msbuild files are already having a PackageReference defined. So it should be possible to ignore this error

thanks

**Comment by jeffkl** [comment]
The build logic depends on a standard property `IsImplicitlyDefined` which is not being set on the implicit package reference to `FSharp.Core`.

https://github.com/microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.props#L97

Other SDKs are properly setting it:

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L57

A workaround is to set the property in the top of your `Packages.props`:

```
<ItemGroup>
  <PackageReference Update="FSharp.Core" IsImplicitlyDefined="true" />
</ItemGroup>
```

We should also open an issue to get this fixed in the FSharp SDK.

**Comment by jeffkl** [comment]
I found a related bug: https://github.com/microsoft/visualfsharp/issues/3678

**Comment by jeffkl** [comment]
PR is out: https://github.com/microsoft/visualfsharp/pull/6730

**Comment by jmecosta** [comment]
Really nice, thanks for the help

**Comment by jeffkl** [comment]
Sorry, I think you'll have to update the FSharp.Core package reference _before_ `Packages.props` is imported so the workaround can't be in `Packages.props` itself.  Try moving it into the project instead.

Also, the FSharp SDK folks have rejected my pull request and won't be adding the IsImplicitlyDefined metadata.  I'll have to come up with another workaround instead.

**Comment by jeffkl** [comment]
I'm going to add the workaround directly to CentralPackageVersions because the FSharp folks want to leave off the necessary metadata to tell if the package was added by a user versus and SDK.

**Comment by jeffkl** [comment]
We have released a new version with the fix, please try it out: https://www.nuget.org/packages/Microsoft.Build.CentralPackageVersions/2.0.36

**Comment by jmecosta** [comment]
Excelent. Thanks for the quick fix. Still hand add the opportunity to upgrade but will confirm once i have

**Comment by jmecosta** [comment]
working fine now, thanks again

**Comment by FunctionalFirst** [comment]
> We have released a new version with the fix, please try it out: https://www.nuget.org/packages/Microsoft.Build.CentralPackageVersions/2.0.36

@jeffkl I'm new to .NET Core. This issue is affecting me. Can you explain how to update this package? I assume it requires updating it in the global Nuget cache?

**Comment by jeffkl** [comment]
You reference MSBuild project SDKs in either a project or global.json.  More info is here: https://github.com/Microsoft/MSBuildSdks#how-can-i-use-these-sdks
