### ISSUE TITLE
Allow loading in VS for .msbuildproj using NoTargets SDK

### ISSUE THREAD

**Issue by kzu** [microsoft/MSBuildSdks#97]
It's quite common for `NoTargets` SDK projects to be just MSBuild scripts. Loading and editing these projects in VS would be useful for managing package references as well as editing and building from VS. 

Most of this support is already in place as long as the project extension is `.msbuildproj` (I'm using this in [AutoCodeFix](https://github.com/kzu/AutoCodeFix/blob/master/src/AutoCodeFix.Package/AutoCodeFix.Package.msbuildproj), for example). It would be nice if the two lines it takes to make it load in VS were included in the SDK, namely:

```xml
<Target Name="CompileDesignTime" />

<Import Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\Managed\Microsoft.Managed.DesignTime.targets" Condition="Exists('$(MSBuildExtensionsPath)\Microsoft\VisualStudio\Managed\Microsoft.Managed.DesignTime.targets')" />
```

**Comment by binki** [comment]
Why not just `.proj`?

**Comment by kzu** [comment]
At least NuGet hardcodes knowledge of that extension: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L237

**Comment by kzu** [comment]
If https://github.com/NuGet/NuGet.Client/pull/2870 is merged, it would work out of the box for `.proj` too :)
